//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcpQuestion
    {
        public AcpQuestion()
        {
            this.AcpQuestionListItems = new HashSet<AcpQuestionListItem>();
            this.AcpSectionQuestions = new HashSet<AcpSectionQuestion>();
        }
    
        public System.Guid Id { get; set; }
        public string QuestionText { get; set; }
        public int AcpAnswerType { get; set; }
        public bool IsCommonQuestion { get; set; }
        public string ToolTip { get; set; }
        public bool IsLargeFont { get; set; }
        public bool IsLargeNoteBox { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> DecimalPlaces { get; set; }
        public Nullable<decimal> MinNumber { get; set; }
        public Nullable<decimal> MaxNumber { get; set; }
        public string Formula { get; set; }
        public Nullable<int> MaxLength { get; set; }
    
        public virtual ICollection<AcpQuestionListItem> AcpQuestionListItems { get; set; }
        public virtual ICollection<AcpSectionQuestion> AcpSectionQuestions { get; set; }
    }
}
