//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcpTemplateVersion
    {
        public AcpTemplateVersion()
        {
            this.AcpFilledForms = new HashSet<AcpFilledForm>();
            this.AcpSections = new HashSet<AcpSection>();
        }
    
        public System.Guid Id { get; set; }
        public int VersionNumber { get; set; }
        public int AcpTemplateType { get; set; }
        public bool IsShowShift { get; set; }
        public bool IsShowReminder { get; set; }
        public bool IsShowAlert { get; set; }
        public bool IsShowMessage { get; set; }
        public bool IsShowLetter { get; set; }
        public bool IsShowNote { get; set; }
        public bool IsLocked { get; set; }
        public bool IsShowClientEvents { get; set; }
        public bool IsShowDescription { get; set; }
        public bool IsShowDocuments { get; set; }
        public int EditDays { get; set; }
        public bool IsRestrictEditDays { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.Guid AcpTemplateId { get; set; }
        public string Name { get; set; }
        public bool IsAllowOtherIndividuals { get; set; }
        public bool AppliesToForm { get; set; }
        public bool AppliesToAssessment { get; set; }
        public short ReAssessmentPeriod { get; set; }
        public System.Guid FormCategoryId { get; set; }
        public bool IsCaseForm { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<bool> HasPreparedBy { get; set; }
        public Nullable<bool> HasReviewedBy { get; set; }
        public Nullable<bool> HasApprovedBy { get; set; }
        public Nullable<bool> HasAuthorizedBy { get; set; }
        public Nullable<bool> LockWhenPreparedBy { get; set; }
        public Nullable<bool> LockWhenReviewedBy { get; set; }
        public Nullable<bool> LockWhenApprovedBy { get; set; }
        public Nullable<bool> LockWhenAuthorizedBy { get; set; }
        public Nullable<int> ReviewDate { get; set; }
    
        public virtual ICollection<AcpFilledForm> AcpFilledForms { get; set; }
        public virtual ICollection<AcpSection> AcpSections { get; set; }
        public virtual AcpTemplate AcpTemplate { get; set; }
        public virtual tblFormCategory tblFormCategory { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
