//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcpWorkflowNotification
    {
        public AcpWorkflowNotification()
        {
            this.AcpActionItems = new HashSet<AcpActionItem>();
            this.AcpWorkflowNotificationItems = new HashSet<AcpWorkflowNotificationItem>();
        }
    
        public System.Guid Id { get; set; }
        public string ActionItemText { get; set; }
        public bool IsActionItem { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual ICollection<AcpActionItem> AcpActionItems { get; set; }
        public virtual ICollection<AcpWorkflowNotificationItem> AcpWorkflowNotificationItems { get; set; }
    }
}
