//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MhcssIntakeAssessment
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> QdcQuarterId { get; set; }
        public Nullable<System.DateTime> ReferralDate { get; set; }
        public Nullable<System.Guid> ReferralSourceId { get; set; }
        public Nullable<System.Guid> ReferralReasonId { get; set; }
        public Nullable<System.Guid> SuburbAtReferralId { get; set; }
        public Nullable<System.DateTime> ReferralHistory { get; set; }
        public Nullable<System.Guid> ReferralExitPointId { get; set; }
        public Nullable<System.DateTime> DateIntakeAssessmentCompleted { get; set; }
        public Nullable<System.Guid> CarersEngagementId { get; set; }
        public Nullable<System.Guid> AdditionalClientDemographicsId { get; set; }
        public Nullable<System.Guid> TreatmentOrdersId { get; set; }
        public Nullable<System.Guid> SuburbAtIntakeId { get; set; }
        public Nullable<System.Guid> EligibilityMhcssId { get; set; }
        public Nullable<System.Guid> IntakeAssessmentCategoryId { get; set; }
        public Nullable<System.Guid> MhcssAllocationId { get; set; }
        public Nullable<System.DateTime> DateMhcssAllocationAccepted { get; set; }
        public Nullable<System.DateTime> DatePlacedOnNeedsRegister { get; set; }
        public Nullable<int> FollowUp { get; set; }
        public Nullable<System.Guid> SelfManagementSupportId { get; set; }
        public Nullable<System.Guid> NonMhcssReferralId { get; set; }
        public Nullable<System.DateTime> DateNonMhcssReferralInitiated { get; set; }
        public Nullable<System.DateTime> DateNonMhcssReferralAccepted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual tblPerson tblPerson { get; set; }
        public virtual tblQDCTable tblQDCTable { get; set; }
        public virtual tblQDCTable tblQDCTable1 { get; set; }
        public virtual tblQDCTable tblQDCTable2 { get; set; }
        public virtual tblQDCTable tblQDCTable3 { get; set; }
        public virtual tblQDCTable tblQDCTable4 { get; set; }
        public virtual tblQDCTable tblQDCTable5 { get; set; }
        public virtual tblQDCTable tblQDCTable6 { get; set; }
        public virtual tblQDCTable tblQDCTable7 { get; set; }
        public virtual tblQDCTable tblQDCTable8 { get; set; }
        public virtual tblQDCTable tblQDCTable9 { get; set; }
        public virtual tblQDCTable tblQDCTable10 { get; set; }
        public virtual tblQDCTable tblQDCTable11 { get; set; }
        public virtual tblSuburb tblSuburb { get; set; }
        public virtual tblSuburb tblSuburb1 { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
