//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public Quotation()
        {
            this.QuotationExternalOutgoings = new HashSet<QuotationExternalOutgoing>();
            this.QuotationIncomeSources = new HashSet<QuotationIncomeSource>();
            this.QuotationInternalOutgoings = new HashSet<QuotationInternalOutgoing>();
            this.QuotationOtherCharges = new HashSet<QuotationOtherCharge>();
            this.QuotationRecurringExternalOutgoings = new HashSet<QuotationRecurringExternalOutgoing>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public System.Guid ParentId { get; set; }
        public int PackageDuration { get; set; }
        public System.DateTime EstimatedCommencementDate { get; set; }
        public Nullable<System.Guid> FundedProgramId { get; set; }
        public Nullable<System.Guid> FundedPackageId { get; set; }
        public decimal DurationAmount { get; set; }
        public Nullable<System.Guid> PackageTierId { get; set; }
        public System.Guid ScheduleId { get; set; }
        public string QuotationNumber { get; set; }
        public decimal QuotationAmount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual tblCDCFundedPackageProgram tblCDCFundedPackageProgram { get; set; }
        public virtual tblCDCProgramName tblCDCProgramName { get; set; }
        public virtual tblPackageTier tblPackageTier { get; set; }
        public virtual tblSchedule tblSchedule { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<QuotationExternalOutgoing> QuotationExternalOutgoings { get; set; }
        public virtual ICollection<QuotationIncomeSource> QuotationIncomeSources { get; set; }
        public virtual ICollection<QuotationInternalOutgoing> QuotationInternalOutgoings { get; set; }
        public virtual ICollection<QuotationOtherCharge> QuotationOtherCharges { get; set; }
        public virtual ICollection<QuotationRecurringExternalOutgoing> QuotationRecurringExternalOutgoings { get; set; }
    }
}
