//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationInternalOutgoing
    {
        public System.Guid Id { get; set; }
        public System.Guid QuotationId { get; set; }
        public Nullable<System.Guid> ServiceId { get; set; }
        public string OtherService { get; set; }
        public decimal OtherServiceRate { get; set; }
        public int Option { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public Nullable<System.Guid> QuotationOrganisationSiteId { get; set; }
        public Nullable<System.Guid> CarerId { get; set; }
        public bool IsIncludeFrequency { get; set; }
        public Nullable<System.Guid> RecurrenceId { get; set; }
        public decimal ServiceQuote { get; set; }
        public string RecurrenceDescription { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual Quotation Quotation { get; set; }
        public virtual tblCarer tblCarer { get; set; }
        public virtual tblOrganisationSite tblOrganisationSite { get; set; }
        public virtual tblService tblService { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
