//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationRecurringExternalOutgoing
    {
        public System.Guid Id { get; set; }
        public System.Guid QuotationId { get; set; }
        public Nullable<System.Guid> QuotationExternalOutgoingId { get; set; }
        public Nullable<System.Guid> QuotationRecurrenceId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Recurrence { get; set; }
        public string ItemName { get; set; }
        public string Material { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual Quotation Quotation { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
