//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccnaSupplementaryHistory
    {
        public System.Guid fldAccnaSupplementaryHistoryID { get; set; }
        public System.Guid fldAccnaSupplementaryID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public string fldPharmacistName { get; set; }
        public string fldPharmacistNumber { get; set; }
        public string fldPodiatristName { get; set; }
        public string fldPodiatristNumber { get; set; }
        public string fldAlliedHealth { get; set; }
        public string fldOtherContact1 { get; set; }
        public string fldOtherContact2 { get; set; }
        public string fldEmergencyAccess { get; set; }
        public string fldEmergencyTradesmen { get; set; }
        public Nullable<int> fldFriendsVisit { get; set; }
        public string fldFriendsVisitComments { get; set; }
        public Nullable<int> fldSocialActivities { get; set; }
        public string fldSocialActivitiesComments { get; set; }
        public Nullable<int> fldSocialAssistance { get; set; }
        public string fldSocialAssistanceComments { get; set; }
        public Nullable<int> fldCultural { get; set; }
        public string fldCulturalComments { get; set; }
        public Nullable<int> fldCulturalLinks { get; set; }
        public string fldCulturalLinksComments { get; set; }
        public Nullable<int> fldParticipate { get; set; }
        public string fldParticipateComments { get; set; }
        public bool fldGPMedicalReport { get; set; }
        public string fldGPMedicalComments { get; set; }
        public Nullable<int> fldSkin { get; set; }
        public string fldSkinComments { get; set; }
        public string fldSkinManage { get; set; }
        public Nullable<int> fldWeight { get; set; }
        public Nullable<int> fldWeightAmount { get; set; }
        public Nullable<bool> fldAppetiteDecrease { get; set; }
        public Nullable<bool> fldAppetiteIncrease { get; set; }
        public string fldWeightComments { get; set; }
        public bool fldFoodPrep { get; set; }
        public bool fldOwnTeeth { get; set; }
        public bool fldDentures { get; set; }
        public bool fldPlate { get; set; }
        public bool fldCrowns { get; set; }
        public bool fldTeethProblems { get; set; }
        public string fldTeethComments { get; set; }
        public bool fldLooseTeeth { get; set; }
        public bool fldCavaties { get; set; }
        public bool fldGingivitis { get; set; }
        public bool fldThrush { get; set; }
        public bool fldBleedingGums { get; set; }
        public bool fldOralAssistance { get; set; }
        public string fldOralComments { get; set; }
        public Nullable<System.DateTime> fldDentalDate { get; set; }
        public Nullable<System.Guid> fldDentist { get; set; }
        public string fldDentalComments { get; set; }
        public bool fldSleep { get; set; }
        public string fldSleepComments { get; set; }
        public bool fldSleepMethod { get; set; }
        public bool fldSleepMeds { get; set; }
        public bool fldSleepLights { get; set; }
        public bool fldSleepDrink { get; set; }
        public bool fldSleepRelaxation { get; set; }
        public string fldSleepOther { get; set; }
        public string fldSleepRoutine { get; set; }
        public Nullable<int> fldGarden { get; set; }
        public string fldGardenComments { get; set; }
        public Nullable<int> fldHomeMods { get; set; }
        public string fldHomeModsComments { get; set; }
        public Nullable<int> fldPets { get; set; }
        public string fldPetDetails { get; set; }
        public Nullable<int> fldPetAssistance { get; set; }
        public string fldPetAssistanceComments { get; set; }
        public string fldVet { get; set; }
        public Nullable<int> fldPetCare { get; set; }
        public string fldPetCareDetails { get; set; }
        public Nullable<int> fldContinenceAssist { get; set; }
        public string fldContinenceAssistDetails { get; set; }
        public Nullable<int> fldContinenceProgram { get; set; }
        public string fldContinenceProgramDetails { get; set; }
        public Nullable<int> fldContinenceEquipment { get; set; }
        public string fldContinenceEquipmentDetails { get; set; }
        public string fldContienceOther { get; set; }
        public string fldContienceNeeds { get; set; }
        public string fldAccnaSupplementaryAdditionalInfo { get; set; }
        public Nullable<System.Guid> fldPensionID { get; set; }
        public string fldOtherOral { get; set; }
    }
}
