//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAllergy
    {
        public System.Guid fldAllergyID { get; set; }
        public System.Guid fldPersonID { get; set; }
        public System.Guid fldAllergyTypeID { get; set; }
        public string fldAllergyDescription { get; set; }
        public string fldAdditionalDetails { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.DateTime> fldDateAcquired { get; set; }
        public string fldSymptoms { get; set; }
        public string fldTriggers { get; set; }
        public string fldTreatment { get; set; }
    }
}
