//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccomIndividualSupportPlan
    {
        public System.Guid fldAccomIndividualSupportPlanID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.DateTime> fldMeetingDate { get; set; }
        public Nullable<System.Guid> fldCompletedBy { get; set; }
        public string fldSummary { get; set; }
        public string fldChoice { get; set; }
        public string fldCompetence { get; set; }
        public string fldPersonalCommunity { get; set; }
        public string fldRespect { get; set; }
        public string fldOther { get; set; }
        public string fldHealthCurrentSupport { get; set; }
        public string fldHealthActions { get; set; }
        public string fldBehaviourCurrentSupport { get; set; }
        public string fldBehaviourActions { get; set; }
        public string fldFinancialCurrentSupport { get; set; }
        public string fldFinancialActions { get; set; }
        public string fldRelationshipCurrentSupport { get; set; }
        public string fldRelationshipActions { get; set; }
        public string fldImageCurrentSupport { get; set; }
        public string fldImageActions { get; set; }
        public string fldOtherCurrentSupport { get; set; }
        public string fldOtherActions { get; set; }
        public string fldPresence { get; set; }
    }
}
