//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentRespiteIntake
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.DateTime> fldRequestDate { get; set; }
        public bool fldReligiousAffiliations { get; set; }
        public string fldReligion { get; set; }
        public Nullable<int> fldHeight { get; set; }
        public Nullable<int> fldWeight { get; set; }
        public string fldEyeColour { get; set; }
        public string fldHairColour { get; set; }
        public string fldComplexion { get; set; }
        public string fldDistinguishingFeatures { get; set; }
        public bool fldMedicalConditions { get; set; }
        public string fldMedicalConditionDescription { get; set; }
        public bool fldMedications { get; set; }
        public bool fldMedicalAllergies { get; set; }
        public bool fldEpilepsy { get; set; }
        public bool fldEpilepsyManagementPlan { get; set; }
        public string fldSupportNeeds { get; set; }
        public Nullable<int> fldRespiteCare { get; set; }
        public string fldRespiteReaction { get; set; }
        public string fldRespiteProblem { get; set; }
        public string fldReactionToWorkers { get; set; }
        public bool fldBehaviourSupport { get; set; }
        public string fldBehaviourDescription { get; set; }
        public string fldBehaviourLocation { get; set; }
        public string fldBehaviourTriggers { get; set; }
        public bool fldPsychologist { get; set; }
        public string fldPsychologistDetails { get; set; }
        public bool fldPsychologistConsent { get; set; }
        public bool fldFears { get; set; }
        public string fldFearComments { get; set; }
        public bool fldWheelchair { get; set; }
        public bool fldHoist { get; set; }
        public bool fldHospitalBed { get; set; }
        public bool fldWalkingStick { get; set; }
        public bool fldOtherAids { get; set; }
        public string fldOtherAidsDescription { get; set; }
        public Nullable<System.DateTime> fldShowerTime { get; set; }
        public Nullable<System.DateTime> fldBathTime { get; set; }
        public Nullable<System.Guid> fldAssistanceShowerId { get; set; }
        public Nullable<System.Guid> fldAssistanceBathId { get; set; }
        public Nullable<System.Guid> fldAssistanceHairId { get; set; }
        public Nullable<System.Guid> fldAssistanceShavingId { get; set; }
        public Nullable<System.Guid> fldAssistanceDressingId { get; set; }
        public Nullable<System.Guid> fldAssistanceClothesId { get; set; }
        public string fldAssistanceComments { get; set; }
        public Nullable<System.Guid> fldAssistanceToiletingId { get; set; }
        public bool fldLearning { get; set; }
        public bool fldCatheter { get; set; }
        public bool fldIncontinencePads { get; set; }
        public bool fldToiletSigning { get; set; }
        public bool fldToiletWords { get; set; }
        public bool fldToiletGestures { get; set; }
        public bool fldToiletTimes { get; set; }
        public bool fldToiletNoIndication { get; set; }
        public string fldToiletingComments { get; set; }
        public Nullable<System.Guid> fldAssistancePeriodId { get; set; }
        public string fldPeriodComments { get; set; }
        public string fldSleepingRoutine { get; set; }
        public string fldWakeUpRoutine { get; set; }
        public bool fldSleepsWithLight { get; set; }
        public bool fldWakesAtNight { get; set; }
        public Nullable<System.DateTime> fldWakeTime { get; set; }
        public bool fldSleepingPillows { get; set; }
        public bool fldSleepingSide { get; set; }
        public bool fldSleepingRepositioning { get; set; }
        public bool fldSleepingOther { get; set; }
        public string fldSleepingComments { get; set; }
        public bool fldMoneyStaff { get; set; }
        public bool fldMoneyClient { get; set; }
        public string fldMoneyComments { get; set; }
        public Nullable<System.Guid> fldAssistanceTransportId { get; set; }
        public bool fldTransportBus { get; set; }
        public bool fldTransportTrain { get; set; }
        public bool fldTransportCar { get; set; }
        public bool fldTransportVan { get; set; }
        public bool fldTransportFerry { get; set; }
        public bool fldTransportSickness { get; set; }
        public Nullable<System.Guid> fldAssistanceRoadSafety { get; set; }
        public string fldRoadSafetyComments { get; set; }
        public string fldMedicalAllergy1 { get; set; }
        public string fldMedicalAllergyReaction1 { get; set; }
        public string fldMedicalAllergyTreatment1 { get; set; }
        public string fldMedicalAllergy2 { get; set; }
        public string fldMedicalAllergyReaction2 { get; set; }
        public string fldMedicalAllergyTreatment2 { get; set; }
        public bool fldFoodAllergies { get; set; }
        public string fldFoodAllergy1 { get; set; }
        public string fldFoodAllergyReaction1 { get; set; }
        public string fldFoodAllergyTreatment1 { get; set; }
        public string fldFoodAllergy2 { get; set; }
        public string fldFoodAllergyReaction2 { get; set; }
        public string fldFoodAllergyTreatment2 { get; set; }
        public bool fldDietNoRestriction { get; set; }
        public bool fldDietSpecial { get; set; }
        public bool fldDietReligious { get; set; }
        public bool fldDietObservance { get; set; }
        public bool fldDietTongueTrust { get; set; }
        public bool fldDietLowFat { get; set; }
        public bool fldDietDiabetic { get; set; }
        public bool fldDietOther { get; set; }
        public string fldDietComments { get; set; }
        public Nullable<System.Guid> fldAssistanceEatingId { get; set; }
        public bool fldEatingPureed { get; set; }
        public bool fldEatingChopped { get; set; }
        public bool fldEatingSittingPosition { get; set; }
        public bool fldEatingSpoon { get; set; }
        public bool fldEatingBowl { get; set; }
        public Nullable<int> fldEatingCrusts { get; set; }
        public string fldEatingCrustsDescription { get; set; }
        public string fldEatingComments { get; set; }
        public Nullable<System.Guid> fldAssistanceDrinkingId { get; set; }
        public bool fldDrinkingThickened { get; set; }
        public bool fldDrinkingThinned { get; set; }
        public bool fldDrinkingOther { get; set; }
        public string fldDrinkingComments { get; set; }
        public string fldDietLikes { get; set; }
        public bool fldCanSwim { get; set; }
        public string fldRespiteActivities { get; set; }
        public string fldReligiousActivities { get; set; }
        public string fldOtherInformation { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldCreatedById { get; set; }
        public Nullable<System.Guid> fldAssistanceUndressingId { get; set; }
        public bool fldWalkingFrame { get; set; }
        public string fldSwimming { get; set; }
    }
}
