//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblACDC
    {
        public System.Guid fldID { get; set; }
        public string fldDSCFileNumber { get; set; }
        public bool fldIncludeInACDC { get; set; }
        public Nullable<System.Guid> fldCarerAgeGroup { get; set; }
        public Nullable<System.DateTime> fldCarerDateOfBirth { get; set; }
        public Nullable<System.Guid> fldCarerExistence { get; set; }
        public Nullable<System.Guid> fldCarerPrimaryStatus { get; set; }
        public Nullable<System.Guid> fldCarerRelationship { get; set; }
        public Nullable<System.Guid> fldCarerResidency { get; set; }
        public Nullable<System.Guid> fldCommunication { get; set; }
        public Nullable<System.Guid> fldCommunicationMethod { get; set; }
        public Nullable<System.Guid> fldDomesticLife { get; set; }
        public Nullable<System.Guid> fldEconomicLife { get; set; }
        public Nullable<System.Guid> fldEducation { get; set; }
        public Nullable<System.Guid> fldFundingStatus { get; set; }
        public Nullable<System.Guid> fldInteractions { get; set; }
        public Nullable<System.Guid> fldInterpreterServices { get; set; }
        public Nullable<System.Guid> fldLabourForceStatus { get; set; }
        public Nullable<System.Guid> fldLearning { get; set; }
        public Nullable<System.Guid> fldMainIncomeSource { get; set; }
        public Nullable<System.Guid> fldMobility { get; set; }
        public Nullable<System.Guid> fldReceiptCarerAllowance { get; set; }
        public Nullable<System.Guid> fldSelfCare { get; set; }
        public Nullable<System.Guid> fldSupportWorking { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public bool fldActive { get; set; }
    }
}
