//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentMD
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldReferralSourceId { get; set; }
        public Nullable<System.Guid> fldIncomeSourceId { get; set; }
        public Nullable<System.Guid> fldAgencyId { get; set; }
        public Nullable<System.Guid> fldHomecareId { get; set; }
        public Nullable<System.Guid> fldCaringForFamilyId { get; set; }
        public Nullable<System.Guid> fldLanguageId { get; set; }
        public Nullable<System.Guid> fldDisabilityId { get; set; }
        public Nullable<System.Guid> fldAtSchoolId { get; set; }
        public Nullable<System.Guid> fldFamilyTypeId { get; set; }
        public Nullable<System.Guid> fldPropertyStatusId { get; set; }
        public Nullable<System.Guid> fldRentalSourceId { get; set; }
        public Nullable<System.Guid> fldEnglishProficiencyId { get; set; }
        public Nullable<System.Guid> fldPaidJobId { get; set; }
        public Nullable<System.Guid> fldHighestSchoolLevelId { get; set; }
        public Nullable<int> fldNoChildren { get; set; }
        public string fldOtherFamilyType { get; set; }
        public string fldOtherIncomeSource { get; set; }
        public string fldOtherReferralSource { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldLivingWithFamilyId { get; set; }
    }
}
