//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccnaHistory
    {
        public System.Guid fldAccnaHistoryID { get; set; }
        public System.Guid fldAccnaID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldINIMasterID { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<int> fldFirstContact { get; set; }
        public Nullable<System.Guid> fldFirstContactID { get; set; }
        public string fldContactReason { get; set; }
        public string fldContactReasonNeeds { get; set; }
        public string fldContactReasonServices { get; set; }
        public string fldContactReasonHope { get; set; }
        public bool fldCircumstanceHospital { get; set; }
        public bool fldCircumstanceFalls { get; set; }
        public bool fldCircumstanceAcute { get; set; }
        public bool fldCircumstanceCarer { get; set; }
        public bool fldCircumstanceConcern { get; set; }
        public bool fldCircumstanceOther { get; set; }
        public string fldCircumstanceComments { get; set; }
        public Nullable<int> fldExperienced { get; set; }
        public bool fldEligibilityEvidence { get; set; }
        public bool fldEligibilityActivities { get; set; }
        public string fldGPComments { get; set; }
        public Nullable<System.Guid> fldAssessorAssistance { get; set; }
        public string fldAssessorAssistanceComments { get; set; }
        public Nullable<int> fldLivingConcerns { get; set; }
        public string fldLivingConcernsComments { get; set; }
        public bool fldFinancialIssues { get; set; }
        public string fldPrefLanguage { get; set; }
        public Nullable<int> fldHouseworkWH { get; set; }
        public Nullable<int> fldHouseworkNM { get; set; }
        public Nullable<int> fldWalkingWH { get; set; }
        public Nullable<int> fldWalkingNM { get; set; }
        public Nullable<int> fldShoppingWH { get; set; }
        public Nullable<int> fldShoppingNM { get; set; }
        public Nullable<int> fldMedicineWH { get; set; }
        public Nullable<int> fldMedicineNM { get; set; }
        public bool fldMedicinePhysical { get; set; }
        public bool fldMedicineCognitive { get; set; }
        public Nullable<int> fldMoneyWH { get; set; }
        public Nullable<int> fldMoneyNM { get; set; }
        public bool fldMoneyPhysical { get; set; }
        public bool fldMoneyCognitive { get; set; }
        public Nullable<int> fldWalkWH { get; set; }
        public Nullable<int> fldWalkNM { get; set; }
        public Nullable<int> fldBathWH { get; set; }
        public Nullable<int> fldBathNM { get; set; }
        public Nullable<int> fldDressing { get; set; }
        public Nullable<int> fldEating { get; set; }
        public Nullable<int> fldToileting { get; set; }
        public Nullable<int> fldMovingAround { get; set; }
        public bool fldCaring { get; set; }
        public bool fldCaringDisabilites { get; set; }
        public string fldCaringComments { get; set; }
        public Nullable<int> fldCarerRoleAtRisk { get; set; }
        public string fldCarerRoleAtRiskComments { get; set; }
        public bool fldRelatedFinancial { get; set; }
        public string fldRelatedFinancialComments { get; set; }
        public Nullable<int> fldBodilyPainProfessional { get; set; }
        public Nullable<int> fldBodilyPainReferral { get; set; }
        public string fldFallOutcome { get; set; }
        public bool fldGlasses { get; set; }
        public bool fldHearingAid { get; set; }
        public string fldHearingComments { get; set; }
        public Nullable<int> fldHomeModifications { get; set; }
        public Nullable<int> fldAidsEquipment { get; set; }
        public Nullable<int> fldMoreIndependent { get; set; }
        public Nullable<int> fldFinancialResources { get; set; }
        public bool fldAssessorEnoughSupport { get; set; }
        public bool fldAssessorInterested { get; set; }
        public bool fldHealthProfessional { get; set; }
        public string fldHealthProfessionalComments { get; set; }
        public string fldAccnaAdditionalInfo { get; set; }
        public bool fldRoleWife { get; set; }
        public bool fldRoleDaughter { get; set; }
        public bool fldRoleOtherFemale { get; set; }
        public bool fldRoleHusband { get; set; }
        public bool fldRoleSon { get; set; }
        public bool fldRoleOtherMale { get; set; }
        public bool fldRoleMother { get; set; }
        public bool fldRoleDaughterInLaw { get; set; }
        public bool fldRoleFriendFemale { get; set; }
        public bool fldRoleFather { get; set; }
        public bool fldRoleSonInLaw { get; set; }
        public bool fldRoleFriend { get; set; }
        public bool fldCena { get; set; }
        public Nullable<System.Guid> fldFirstContactOrganisationID { get; set; }
        public Nullable<int> fldSocialSupport { get; set; }
        public bool fldEquipmentHearingAid { get; set; }
        public bool fldEquipmentHomeModifications { get; set; }
        public Nullable<int> fldCarerOtherPeople { get; set; }
        public Nullable<System.Guid> fldCarer { get; set; }
        public string fldCarerOtherPeopleComments { get; set; }
        public Nullable<int> fldFalls { get; set; }
        public Nullable<int> fldFunctionalTotal { get; set; }
        public Nullable<int> fldWHTotal { get; set; }
        public Nullable<int> fldNMTotal { get; set; }
    }
}
