//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditLogAccessedClientRecord
    {
        public System.Guid fldAuditLogAccessedClientRecordID { get; set; }
        public System.Guid fldPersonID { get; set; }
        public string fldRecordType { get; set; }
        public Nullable<System.Guid> fldAccessedSuiteID { get; set; }
        public Nullable<System.Guid> fldAccessToolID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public bool fldActive { get; set; }
    }
}
