//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblACDCOutlet
    {
        public System.Guid fldId { get; set; }
        public int fldACDCOutletNumber { get; set; }
        public Nullable<System.Guid> fldAgencySectorId { get; set; }
        public Nullable<System.Guid> fldServiceTypeId { get; set; }
        public Nullable<System.Guid> fldLinkedACDCAgency { get; set; }
        public bool fldFullFinancialYear { get; set; }
        public Nullable<System.DateTime> fldOperationStartDate { get; set; }
        public Nullable<System.DateTime> fldOperationEndDate { get; set; }
        public int fldWeeksPerYear { get; set; }
        public int fldDaysPerWeek { get; set; }
        public int fldHoursPerDay { get; set; }
        public bool fldNoRegularCollectionPattern { get; set; }
        public bool fldNoWeeklyCollectionPattern { get; set; }
        public bool fldNoDailyCollectionPattern { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public bool fldActive { get; set; }
    }
}
