//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlert
    {
        public System.Guid fldAlertID { get; set; }
        public string fldSubject { get; set; }
        public string fldNote { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public bool fldMobileAlert { get; set; }
        public bool fldCarePlanAlert { get; set; }
        public bool fldArchived { get; set; }
        public Nullable<System.Guid> fldArchiveReasonId { get; set; }
        public Nullable<System.Guid> fldPositionId { get; set; }
        public Nullable<System.DateTime> fldExpiryDate { get; set; }
    }
}
