//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessmentTime
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldAssessmentID { get; set; }
        public Nullable<System.Guid> fldAssessmentToolID { get; set; }
        public Nullable<decimal> fldDuration { get; set; }
        public Nullable<System.Guid> fldStatusID { get; set; }
        public Nullable<System.Guid> fldAssessedViaID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPositionID { get; set; }
    }
}
