//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAutoSelectRule
    {
        public System.Guid fldID { get; set; }
        public Nullable<int> fldGap { get; set; }
        public Nullable<int> fldDistance { get; set; }
        public Nullable<int> fldEmploymentBasis { get; set; }
        public Nullable<int> fldPercentFit { get; set; }
        public Nullable<int> fldServiced { get; set; }
        public Nullable<int> fldRecentCarers { get; set; }
        public Nullable<int> fldClassification { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
    }
}
