//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccomSupportPlanAgreement
    {
        public System.Guid fldAccomSupportPlanAgreementID { get; set; }
        public Nullable<System.DateTime> fldMeetingDate { get; set; }
        public Nullable<System.Guid> fldCompletedBy { get; set; }
        public Nullable<int> fldCurrentSupportHours { get; set; }
        public Nullable<int> fldTargetSupportHours { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
    }
}
