//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBreakEvenOutcomeOne
    {
        public System.Guid fldID { get; set; }
        public Nullable<int> fldGamblingProblem { get; set; }
        public Nullable<int> fldGamblingFrequency { get; set; }
        public Nullable<int> fldPrimarySessions { get; set; }
        public Nullable<int> fldSecondarySessions { get; set; }
        public Nullable<decimal> fldPrimaryHours { get; set; }
        public Nullable<decimal> fldSecondaryHours { get; set; }
        public Nullable<decimal> fldPrimaryLoss { get; set; }
        public Nullable<decimal> fldSecondaryLoss { get; set; }
        public Nullable<int> fldGamblingScale { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonId { get; set; }
        public bool fldIntake { get; set; }
        public int fldOutcomeId { get; set; }
    }
}
