//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBudgetReportTemp
    {
        public System.Guid fldBudgetReportTempID { get; set; }
        public Nullable<System.Guid> fldUserID { get; set; }
        public Nullable<System.DateTime> fldDateCheck { get; set; }
        public Nullable<double> Hours { get; set; }
        public string fldDescription { get; set; }
        public Nullable<int> MonthNumber { get; set; }
        public string Service { get; set; }
        public Nullable<System.Guid> fldServiceID { get; set; }
        public string fldOrder { get; set; }
        public bool fldAccTarget { get; set; }
        public bool fldAccActual { get; set; }
    }
}
