//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBRServiceRequest
    {
        public System.Guid fldID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.DateTime> fldRequestDate { get; set; }
        public string fldUFICaseNumber { get; set; }
        public string fldReferralReason { get; set; }
        public bool fldApproved { get; set; }
        public Nullable<System.DateTime> fldApprovedDate { get; set; }
        public Nullable<System.Guid> fldApprovedById { get; set; }
        public Nullable<System.Guid> fldCaseWorkerId { get; set; }
        public Nullable<System.Guid> fldSupervisorId { get; set; }
        public string fldSupervisorComments { get; set; }
        public bool fldSourcingChildcare { get; set; }
        public bool fldTransitionToCareSupport { get; set; }
        public bool fldBrokerageFunds { get; set; }
        public bool fldLongDayCare { get; set; }
        public bool fldPreschool { get; set; }
        public bool fldFamilyDayCare { get; set; }
        public bool fldOccasionalCare { get; set; }
        public bool fldDaySupport1 { get; set; }
        public bool fldDaySupport2 { get; set; }
        public bool fldDaySupportOther { get; set; }
        public string fldDaySupportOtherComment { get; set; }
        public bool fldBirthCertificate { get; set; }
        public bool fldImmunisation { get; set; }
        public bool fldBlueBook { get; set; }
        public bool fldChildcareRebate { get; set; }
        public string fldChildcareCentre { get; set; }
        public string fldChildCareContact { get; set; }
        public string fldSpecialDietary { get; set; }
        public bool fldChildhoodDevelopmentAssess { get; set; }
        public bool fldChildhoodSupportServices { get; set; }
        public bool fldSupportOngoingInclusion { get; set; }
        public bool fldCareConsult { get; set; }
        public bool fldTransitionToSchool { get; set; }
        public bool fldOtherRequest { get; set; }
        public string fldOtherRequestComment { get; set; }
        public string fldChildhoodRoleExpectation { get; set; }
        public string fldAppointmentIssues { get; set; }
        public string fldReceiveOtherSupport { get; set; }
        public string fldHomeVisitRisk { get; set; }
        public string fldProgramPaygroup { get; set; }
        public string fldFacilitator { get; set; }
        public string fldVenue { get; set; }
        public Nullable<System.DateTime> fldGroupStartDate { get; set; }
        public Nullable<System.DateTime> fldGroupEndDate { get; set; }
        public string fldDayGroupMeets { get; set; }
        public string fldSessionTime { get; set; }
        public string fldGroupMedicalCondition { get; set; }
        public string fldGroupDietary { get; set; }
        public string fldGroupAdditionalNeed { get; set; }
        public string fldWillingToChange { get; set; }
        public string fldPreviousProgramHow { get; set; }
        public string fldIntroHomeVisit { get; set; }
        public string fldCaseWorkerAttending { get; set; }
        public bool fldChildcareNotRequired { get; set; }
        public bool fldChildcareRequired { get; set; }
        public string fldGroupAttendChildren { get; set; }
    }
}
