//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCDCExternalOutgoing
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldCategoryId { get; set; }
        public Nullable<System.Guid> fldMaterialId { get; set; }
        public string fldSupplier { get; set; }
        public string fldItem { get; set; }
        public string fldDescription { get; set; }
        public Nullable<System.DateTime> fldInvoiceDate { get; set; }
        public Nullable<decimal> fldQuantity { get; set; }
        public Nullable<decimal> fldUnitCost { get; set; }
        public bool fldTaxApplies { get; set; }
        public decimal fldTaxAmount { get; set; }
        public decimal fldTotalAmount { get; set; }
        public string fldGLCode { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public bool fldActive { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public bool fldPaymentMade { get; set; }
        public Nullable<System.Guid> fldClientFundingSource { get; set; }
        public Nullable<System.Guid> fldRecurrenceGeneratedDateId { get; set; }
        public Nullable<System.Guid> fldExternalOutgoingRuleId { get; set; }
        public Nullable<System.Guid> fldCdcActualisationId { get; set; }
        public bool fldOnCostAmountPercentage { get; set; }
        public Nullable<decimal> fldOnCostAmount { get; set; }
        public bool fldOnCostTaxApplies { get; set; }
        public Nullable<decimal> fldOnCostTaxAmount { get; set; }
        public Nullable<System.Guid> fldSupplierId { get; set; }
        public string fldInvoiceNumber { get; set; }
        public Nullable<decimal> fldAmountPaid { get; set; }
        public Nullable<System.DateTime> fldDatePaid { get; set; }
        public string fldPurchaseOrderNumber { get; set; }
        public System.DateTime fldItemDate { get; set; }
    }
}
