//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCaseManagementHistory
    {
        public System.Guid fldCaseManagementIDHistoryID { get; set; }
        public Nullable<System.Guid> fldCaseManagementID { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldCaseTypeID { get; set; }
        public Nullable<System.Guid> fldCaseManagerID { get; set; }
        public Nullable<System.Guid> fldSupervisorID { get; set; }
        public Nullable<System.DateTime> fldFirstContactDate { get; set; }
        public Nullable<int> fldCaseID { get; set; }
        public Nullable<double> fldIncomeIndividual { get; set; }
        public Nullable<double> fldIncomeHousehold { get; set; }
        public Nullable<System.Guid> fldReferralSource { get; set; }
        public Nullable<System.Guid> fldReferredTo { get; set; }
        public string fldOutcomeNotes { get; set; }
        public Nullable<System.DateTime> fldClosureDate { get; set; }
        public Nullable<System.Guid> fldClosedByID { get; set; }
        public Nullable<System.Guid> fldClosureReasonID { get; set; }
        public Nullable<System.Guid> fldManageFinancialAffairsID { get; set; }
        public Nullable<System.Guid> fldCaseProblemResolvedID { get; set; }
        public Nullable<int> fldStatus { get; set; }
        public string fldClosureNotes { get; set; }
        public Nullable<bool> fldNoService { get; set; }
        public Nullable<System.Guid> fldNoServiceReasonId { get; set; }
        public string fldResourcesProvided { get; set; }
        public Nullable<System.Guid> fldCasePersonTypeId { get; set; }
        public Nullable<System.Guid> fldLivingArrangementsId { get; set; }
        public string fldAvailability { get; set; }
        public string fldPlacementNotes { get; set; }
        public Nullable<System.Guid> fldDepartment { get; set; }
        public Nullable<bool> fldEnquiryImported { get; set; }
    }
}
