//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarePlanReport
    {
        public System.Guid fldID { get; set; }
        public Nullable<int> fldRow { get; set; }
        public string fldColumn11Text { get; set; }
        public string fldColumn21Text { get; set; }
        public string fldColumn31Text { get; set; }
        public string fldColumn41Text { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public string fldColumn12Text { get; set; }
        public string fldColumn13Text { get; set; }
        public string fldColumn14Text { get; set; }
        public string fldColumn22Text { get; set; }
        public string fldColumn23Text { get; set; }
        public string fldColumn32Text { get; set; }
    }
}
