//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarePlanTemplateDetail
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldCarePlanID { get; set; }
        public string fldFieldDetails { get; set; }
        public Nullable<int> fldColumn { get; set; }
        public Nullable<int> fldRow { get; set; }
        public Nullable<int> fldWidth { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public string fldRtf { get; set; }
    }
}
