//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactDetail
    {
        public System.Guid fldContactDetailsID { get; set; }
        public System.Guid fldContactDetailsTypeID { get; set; }
        public string fldContactDetails { get; set; }
        public byte fldCanLeaveMessage { get; set; }
        public byte fldDefault { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldForeignID { get; set; }
        public byte fldCanSMS { get; set; }
        public byte fldOmitFromRoster { get; set; }
        public bool fldOffline { get; set; }
    }
}
