//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCDCDisabilityServiceBudgetClientContributionOccurrence
    {
        public System.Guid fldId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public bool fldActive { get; set; }
        public string fldDescription { get; set; }
        public decimal fldAmount { get; set; }
        public decimal fldHours { get; set; }
        public System.DateTime fldStartDate { get; set; }
        public System.DateTime fldEndDate { get; set; }
        public System.Guid fldCategoryId { get; set; }
        public System.Guid fldServiceRequiredId { get; set; }
        public System.Guid fldCarerPersonId { get; set; }
        public System.DateTime fldStartTime { get; set; }
        public System.DateTime fldEndTime { get; set; }
        public bool fldAutoApprove { get; set; }
        public System.Guid fldCDCDisabilityServiceBudgetClientContributionRecurrenceId { get; set; }
        public Nullable<System.Guid> fldRecurrenceGeneratedDateId { get; set; }
        public Nullable<System.Guid> fldRosterShiftId { get; set; }
    }
}
