//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCDCFundedPackageAllocationCondition
    {
        public System.Guid fldCDCAllocationConditionID { get; set; }
        public Nullable<System.Guid> fldCDCFundedPackagePlanningRegionID { get; set; }
        public int fldPlaces { get; set; }
        public Nullable<System.Guid> fldSpecialNeedsGroup { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public bool fldActive { get; set; }
        public bool fldIsMandatory { get; set; }
        public int fldAllocated { get; set; }
        public bool fldNonCondition { get; set; }
    }
}
