//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCansa
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public int fldQuestion1 { get; set; }
        public int fldQuestion2 { get; set; }
        public int fldQuestion3 { get; set; }
        public int fldQuestion4 { get; set; }
        public int fldQuestion5 { get; set; }
        public int fldQuestion6 { get; set; }
        public int fldQuestion7 { get; set; }
        public int fldQuestion8 { get; set; }
        public int fldQuestion9 { get; set; }
        public int fldQuestion10 { get; set; }
        public int fldQuestion11 { get; set; }
        public int fldQuestion12 { get; set; }
        public int fldQuestion13 { get; set; }
        public int fldQuestion14 { get; set; }
        public int fldQuestion15 { get; set; }
        public int fldQuestion16 { get; set; }
        public int fldQuestion17 { get; set; }
        public int fldQuestion18 { get; set; }
        public int fldQuestion19 { get; set; }
        public int fldQuestion20 { get; set; }
        public int fldQuestion21 { get; set; }
        public int fldQuestion22 { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<int> fldFormType { get; set; }
        public System.DateTime fldDateCompleted { get; set; }
        public Nullable<System.DateTime> fldReviewDate { get; set; }
        public int fldQuestion23 { get; set; }
        public int fldQuestion24 { get; set; }
        public int fldQuestion25 { get; set; }
        public Nullable<int> fldScore { get; set; }
        public Nullable<System.Guid> fldOrgSiteID { get; set; }
        public Nullable<System.Guid> fldNotCompletedReasonID { get; set; }
    }
}
