//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCDCDisabilityServiceBudgetIncomeItem
    {
        public System.Guid fldId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public bool fldActive { get; set; }
        public System.Guid fldCdcBudgetId { get; set; }
        public string fldDescription { get; set; }
        public System.Guid fldCategoryId { get; set; }
        public Nullable<System.Guid> fldProgramBudgetId { get; set; }
        public System.DateTime fldStartDate { get; set; }
        public System.DateTime fldEndDate { get; set; }
        public decimal fldFundedAmount { get; set; }
        public decimal fldFundedHours { get; set; }
    }
}
