//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContract
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldContractTypeID { get; set; }
        public Nullable<System.Guid> fldServiceStreamID { get; set; }
        public Nullable<System.Guid> fldServiceSubstreamID { get; set; }
        public Nullable<System.Guid> fldDivisionID { get; set; }
        public Nullable<System.Guid> fldProgramID { get; set; }
        public Nullable<System.Guid> fldFunderID { get; set; }
        public Nullable<System.Guid> fldFundingTypeID { get; set; }
        public string fldAgreementName { get; set; }
        public string fldAgreementReference { get; set; }
        public string fldInternalReference { get; set; }
        public Nullable<System.Guid> fldParentID { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldFunderContactID { get; set; }
        public Nullable<System.DateTime> fldFunderExecuteDate { get; set; }
        public Nullable<System.Guid> fldContactID { get; set; }
        public Nullable<System.DateTime> fldExecuteDate { get; set; }
        public Nullable<System.DateTime> fldStartDate { get; set; }
        public Nullable<System.DateTime> fldEndDate { get; set; }
        public Nullable<int> fldTerminationNotice { get; set; }
        public Nullable<System.Guid> fldTerminationFrequency { get; set; }
        public bool fldAccreditationRequired { get; set; }
        public Nullable<System.Guid> fldAccreditingBody { get; set; }
        public bool fldLicensingRequired { get; set; }
        public Nullable<System.Guid> fldLicensingBody { get; set; }
        public Nullable<System.Guid> fldPreviousAgreementID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public int fldFlag { get; set; }
        public bool fldIncomplete { get; set; }
        public bool fldIsEditing { get; set; }
        public string fldClientFirstName { get; set; }
        public string fldClientLastName { get; set; }
        public Nullable<System.Guid> fldClientTitleID { get; set; }
        public string fldClientPhone { get; set; }
        public bool fldNewClient { get; set; }
        public Nullable<System.Guid> fldCategory { get; set; }
    }
}
