//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarelinkServer
    {
        public string fldServerName { get; set; }
        public Nullable<int> fldPriority { get; set; }
        public System.DateTime fldLastTimeStamp { get; set; }
        public Nullable<System.DateTime> fldControlTimeStamp { get; set; }
        public Nullable<System.DateTime> fldProcessingTimeStamp { get; set; }
        public string fldCurrentModule { get; set; }
        public string fldLastModule { get; set; }
        public Nullable<System.DateTime> fldLastProcessedTimeStamp { get; set; }
    }
}
