//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientECSummaryNote
    {
        public System.Guid fldClientECSummaryID { get; set; }
        public System.Guid fldPersonID { get; set; }
        public string fldClientECSumDescription { get; set; }
        public string fldClientECProcLoc { get; set; }
        public string fldClientECMedLoc { get; set; }
        public string fldClientECCommLoc { get; set; }
        public string fldClientECEmSum { get; set; }
        public string fldClientECPrefGPSum { get; set; }
        public string fldClientEC1stSum { get; set; }
        public string fldClientEC2ndSum { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserID { get; set; }
        public int fldActive { get; set; }
        public string fldEmergencyProcedures { get; set; }
        public string fldEmergencyHospital { get; set; }
        public Nullable<System.Guid> fldSecondaryPreferredHospital { get; set; }
        public bool fldAdvancedCareDirectiveSigned { get; set; }
        public Nullable<System.Guid> fldAmbulanceConsentID { get; set; }
        public string fldAdvancedCareDirectiveLocation { get; set; }
    }
}
