//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCDCFundedPackagePlanningRegion
    {
        public System.Guid fldID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public bool fldActive { get; set; }
        public System.Guid fldCDCFundedPackageId { get; set; }
        public int fldFundedPlaces { get; set; }
        public int fldNonFundedPlaces { get; set; }
        public bool fldUnlimitedFunded { get; set; }
        public bool fldUnlimitedNonFunded { get; set; }
        public System.Guid fldPlanningRegionId { get; set; }
    }
}
