//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientProfileV2
    {
        public System.Guid fldID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldAdministratorContactId { get; set; }
        public Nullable<System.Guid> fldGuardianContactId { get; set; }
        public Nullable<System.Guid> fldCustodyArrangementContactId { get; set; }
        public Nullable<System.Guid> fldDcpInvolvementContactId { get; set; }
        public Nullable<System.Guid> fldPrimaryCarerContactId { get; set; }
        public Nullable<System.Guid> fldLocalAreaCoordinatorContactId { get; set; }
        public string fldOtherCommunitySupport { get; set; }
    }
}
