//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCaseManagementReviewsHistory
    {
        public System.Guid fldIDHistoryID { get; set; }
        public Nullable<System.Guid> fldID { get; set; }
        public Nullable<System.Guid> fldCaseManagementId { get; set; }
        public Nullable<System.DateTime> fldReviewDate { get; set; }
        public Nullable<System.Guid> fldReviewedById { get; set; }
        public Nullable<System.Guid> fldGoalsAchievedId { get; set; }
        public Nullable<System.Guid> fldPresentingIssuesManagedId { get; set; }
        public Nullable<bool> fldCaseClosed { get; set; }
        public string fldReviewNotes { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public Nullable<int> fldStatus { get; set; }
        public Nullable<int> fldIssuesResolved { get; set; }
    }
}
