//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCDCDisabilityServiceFinancialPackageActualIncome
    {
        public System.Guid fldId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public bool fldActive { get; set; }
        public System.Guid fldCDCFinancialPackageId { get; set; }
        public System.Guid fldCDCDisabilityServiceBudgetIncomeItemId { get; set; }
        public System.Guid fldFinancialPackageCategoryId { get; set; }
        public System.Guid fldCDCActualisationId { get; set; }
        public bool fldIsApproved { get; set; }
        public decimal fldTotalAmount { get; set; }
        public decimal fldHours { get; set; }
        public System.DateTime fldStartDate { get; set; }
        public System.DateTime fldEndDate { get; set; }
    }
}
