//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCenaZaritHistory
    {
        public System.Guid fldCenaZaritHistoryID { get; set; }
        public System.Guid fldCenaZaritID { get; set; }
        public System.Guid fldCenaID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<int> fldZarit1 { get; set; }
        public Nullable<int> fldZarit2 { get; set; }
        public Nullable<int> fldZarit3 { get; set; }
        public Nullable<int> fldZarit4 { get; set; }
        public Nullable<int> fldZarit5 { get; set; }
        public Nullable<int> fldZarit6 { get; set; }
        public Nullable<int> fldZarit7 { get; set; }
        public Nullable<int> fldZarit8 { get; set; }
        public Nullable<int> fldZarit9 { get; set; }
        public Nullable<int> fldZarit10 { get; set; }
        public Nullable<int> fldZarit11 { get; set; }
        public Nullable<int> fldZarit12 { get; set; }
        public Nullable<int> fldZarit13 { get; set; }
        public Nullable<int> fldZarit14 { get; set; }
        public Nullable<int> fldZarit15 { get; set; }
        public Nullable<int> fldZarit16 { get; set; }
        public Nullable<int> fldZarit17 { get; set; }
        public Nullable<int> fldZarit18 { get; set; }
        public Nullable<int> fldZarit19 { get; set; }
        public Nullable<int> fldZarit20 { get; set; }
        public Nullable<int> fldZarit21 { get; set; }
        public Nullable<int> fldZarit22 { get; set; }
        public Nullable<int> fldOverall { get; set; }
        public Nullable<int> fldSubTotal { get; set; }
        public Nullable<int> fldTotal { get; set; }
    }
}
