//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatabaseField
    {
        public System.Guid fldID { get; set; }
        public string fldFieldFriendlyName { get; set; }
        public string fldPropertyName { get; set; }
        public Nullable<int> fldBusinessBase { get; set; }
        public string fldComboListSource { get; set; }
        public Nullable<int> fldListType { get; set; }
        public string fldPropertyType { get; set; }
        public Nullable<int> fldControlType { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public string fldComboListValueMember { get; set; }
        public string fldComboListDisplayMember { get; set; }
        public Nullable<int> fldMaximumLength { get; set; }
    }
}
