//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDVAItemNumber
    {
        public System.Guid fldDVAItemNumberID { get; set; }
        public string fldItemNumber { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldEdit { get; set; }
        public string fldDescription { get; set; }
        public bool fldConsumable { get; set; }
        public bool fldCorePersonalCare { get; set; }
        public bool fldCoreClinicalCare { get; set; }
        public bool fldPersonalCareAddOns { get; set; }
        public bool fldClinicalCareAddOns { get; set; }
        public bool fldOther { get; set; }
        public bool fldCoreOther { get; set; }
    }
}
