//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDisability
    {
        public System.Guid fldDisabilityID { get; set; }
        public System.Guid fldPersonID { get; set; }
        public System.Guid fldDisabilityTypeID { get; set; }
        public Nullable<System.Guid> fldDisabilitySeverityId { get; set; }
        public Nullable<System.DateTime> fldDateOfAccident { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldDisabilityCauseID { get; set; }
        public Nullable<System.Guid> fldDisabilityLevelID { get; set; }
        public Nullable<System.Guid> fldDisabilityLocationID { get; set; }
        public bool fldWorkRelatedInjury { get; set; }
        public Nullable<System.DateTime> fldDateAcquired { get; set; }
        public Nullable<System.Guid> fldDiagnosticConfirmation { get; set; }
        public bool fldArchived { get; set; }
        public Nullable<System.Guid> fldArchivedReason { get; set; }
        public Nullable<System.DateTime> fldArchivedDate { get; set; }
        public Nullable<System.Guid> fldDiagnosedBy { get; set; }
    }
}
