//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDutyOfCare
    {
        public System.Guid fldDutyOfCareID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<int> fldType { get; set; }
        public string fldRiskIssue { get; set; }
        public Nullable<System.DateTime> fldOccuranceDate { get; set; }
        public Nullable<System.DateTime> fldDateReported { get; set; }
        public bool fldCategorySafety { get; set; }
        public bool fldCategoryWellbeing { get; set; }
        public bool fldRiskFocusClient { get; set; }
        public bool fldRiskFocusWorker { get; set; }
        public bool fldRiskFocusOthers { get; set; }
        public string fldRiskOutline { get; set; }
        public string fldActionTaken { get; set; }
        public Nullable<int> fldRiskStatus { get; set; }
        public Nullable<System.DateTime> fldFurtherResponsesdate { get; set; }
        public string fldFurtherResponses { get; set; }
        public bool fldPlanRequired { get; set; }
        public Nullable<System.Guid> fldManager { get; set; }
        public Nullable<System.Guid> fldIncident { get; set; }
        public Nullable<System.Guid> fldWorkDomain { get; set; }
        public string fldCriterion { get; set; }
        public Nullable<System.DateTime> fldEvaluateBefore { get; set; }
        public Nullable<System.DateTime> fldEvaluationConducted { get; set; }
        public bool fldRMPSuccess { get; set; }
        public Nullable<int> fldFinalStatus { get; set; }
        public Nullable<System.DateTime> fldSuspendedDate { get; set; }
    }
}
