//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDASS
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.DateTime> fldDate { get; set; }
        public bool fldInitialAssessment { get; set; }
        public Nullable<int> fldQuestion1 { get; set; }
        public Nullable<int> fldQuestion2 { get; set; }
        public Nullable<int> fldQuestion3 { get; set; }
        public Nullable<int> fldQuestion4 { get; set; }
        public Nullable<int> fldQuestion5 { get; set; }
        public Nullable<int> fldQuestion6 { get; set; }
        public Nullable<int> fldQuestion7 { get; set; }
        public Nullable<int> fldQuestion8 { get; set; }
        public Nullable<int> fldQuestion9 { get; set; }
        public Nullable<int> fldQuestion10 { get; set; }
        public Nullable<int> fldQuestion11 { get; set; }
        public Nullable<int> fldQuestion12 { get; set; }
        public Nullable<int> fldQuestion13 { get; set; }
        public Nullable<int> fldQuestion14 { get; set; }
        public Nullable<int> fldQuestion15 { get; set; }
        public Nullable<int> fldQuestion16 { get; set; }
        public Nullable<int> fldQuestion17 { get; set; }
        public Nullable<int> fldQuestion18 { get; set; }
        public Nullable<int> fldQuestion19 { get; set; }
        public Nullable<int> fldQuestion20 { get; set; }
        public Nullable<int> fldQuestion21 { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
    }
}
