//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEziPayTolerance
    {
        public Nullable<int> fldStartTolerance1 { get; set; }
        public Nullable<int> fldEndTolerance1 { get; set; }
        public Nullable<int> fldLengthTolerance1 { get; set; }
        public System.Guid fldServiceID { get; set; }
        public Nullable<int> fldStartTolerance2 { get; set; }
        public Nullable<int> fldEndTolerance2 { get; set; }
        public Nullable<int> fldLengthTolerance2 { get; set; }
        public System.Guid fldID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<int> fldMaxLength1 { get; set; }
        public Nullable<int> fldMaxLength2 { get; set; }
    }
}
