//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEpicorClient
    {
        public System.Guid fldId { get; set; }
        public string fldName { get; set; }
        public System.DateTime fldDateTime { get; set; }
        public bool fldError { get; set; }
        public string fldDetails { get; set; }
        public string fldCustomerCode { get; set; }
    }
}
