//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeNursing
    {
        public System.Guid fldEmployeeNursingId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public string fldRegistrationNo { get; set; }
        public Nullable<System.DateTime> fldRegistrationExpiry { get; set; }
        public Nullable<System.Guid> fldNursingLicenseTypeId { get; set; }
        public Nullable<System.DateTime> fldSighted { get; set; }
        public Nullable<System.Guid> fldPersonId { get; set; }
    }
}
