//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnquiry
    {
        public tblEnquiry()
        {
            this.AcpActionItems = new HashSet<AcpActionItem>();
            this.AcpFilledForms = new HashSet<AcpFilledForm>();
        }
    
        public System.Guid fldID { get; set; }
        public int fldEnquiryNumber { get; set; }
        public Nullable<System.DateTime> fldEnquiryDate { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldTitleID { get; set; }
        public string fldFirstName { get; set; }
        public string fldLastName { get; set; }
        public string fldOrganisation { get; set; }
        public Nullable<System.Guid> fldRelationship { get; set; }
        public bool fldIsClientAware { get; set; }
        public bool fldIsClientEnquirer { get; set; }
        public Nullable<System.Guid> fldClientTitle { get; set; }
        public string fldClientFirstName { get; set; }
        public string fldClientLastName { get; set; }
        public Nullable<System.Guid> fldEnquiryStatusID { get; set; }
        public Nullable<int> fldOutcome { get; set; }
        public Nullable<System.Guid> fldEnquirySourceID { get; set; }
        public string fldFollowUpRequired { get; set; }
        public string fldFurtherResponse { get; set; }
        public bool fldReferralToIntake { get; set; }
        public string fldClientNumber { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldClientID { get; set; }
        public Nullable<System.Guid> fldReferralSourceID { get; set; }
        public Nullable<System.DateTime> fldDateOfBirth { get; set; }
        public Nullable<System.Guid> fldLGA { get; set; }
        public string fldInformationProvided { get; set; }
        public bool fldCommunicationAssistance { get; set; }
        public string fldCommunicationMethod { get; set; }
        public bool fldUnmetNeeds { get; set; }
        public string fldServiceGap { get; set; }
        public Nullable<System.Guid> fldEnquirerId { get; set; }
        public Nullable<System.Guid> fldDepartmentId { get; set; }
        public Nullable<System.Guid> fldEnquirerIndigenousStatusId { get; set; }
        public Nullable<System.Guid> fldEnquirerCountryId { get; set; }
        public Nullable<System.Guid> fldEnquirerLanguageId { get; set; }
        public Nullable<System.Guid> fldEnquirerGenderId { get; set; }
        public Nullable<System.Guid> fldEnquirerCultureId { get; set; }
        public Nullable<System.Guid> fldEnquirerLivingArrangementsId { get; set; }
        public Nullable<System.Guid> fldEnquirerAccommodationSettingId { get; set; }
        public Nullable<System.Guid> fldEnquirerEmploymentStatusId { get; set; }
        public Nullable<System.Guid> fldEnquirerAgeRangeId { get; set; }
        public Nullable<System.Guid> fldClientIndigenousStatusId { get; set; }
        public Nullable<System.Guid> fldClientCountryId { get; set; }
        public Nullable<System.Guid> fldClientLanguageId { get; set; }
        public Nullable<System.Guid> fldClientGenderId { get; set; }
        public Nullable<System.Guid> fldClientCultureId { get; set; }
        public Nullable<System.Guid> fldClientLivingArrangementsId { get; set; }
        public Nullable<System.Guid> fldClientAccommodationSettingId { get; set; }
        public Nullable<System.Guid> fldClientEmploymentStatusId { get; set; }
        public Nullable<System.Guid> fldClientAgeRangeId { get; set; }
        public bool fldFinancialRisk { get; set; }
        public bool fldLegalRisk { get; set; }
        public bool fldPersonalRisk { get; set; }
        public Nullable<int> fldHouseholdIncome { get; set; }
        public Nullable<int> fldIndividualIncome { get; set; }
        public string fldOtherReferralComments { get; set; }
        public Nullable<System.Guid> fldStressLevelId { get; set; }
        public Nullable<System.Guid> fldSatisfactionId { get; set; }
        public Nullable<System.Guid> fldSupportLevelId { get; set; }
        public Nullable<decimal> fldTimeTaken { get; set; }
        public bool fldRiskOfSelfHarm { get; set; }
        public Nullable<System.Guid> fldEnteredById { get; set; }
        public Nullable<System.Guid> fldEnquiryAction { get; set; }
    
        public virtual ICollection<AcpActionItem> AcpActionItems { get; set; }
        public virtual ICollection<AcpFilledForm> AcpFilledForms { get; set; }
    }
}
