//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmploymentExit
    {
        public System.Guid fldEmploymentExitID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.DateTime> fldExitDate { get; set; }
        public Nullable<System.Guid> fldEmploymentGoalsAchievedID { get; set; }
        public bool fldSuccessful { get; set; }
        public string fldSuccessfulAdditional { get; set; }
        public bool fldEmploymentBarriers { get; set; }
        public string fldEmploymentBarriersAdditional { get; set; }
        public Nullable<System.Guid> fldClosedByID { get; set; }
        public Nullable<System.Guid> fldProfileID { get; set; }
    }
}
