//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmploymentPlanReview
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldEmploymentPlanId { get; set; }
        public string fldGoal { get; set; }
        public string fldStatus { get; set; }
        public string fldFurtherAction { get; set; }
        public string fldResponsibleParty { get; set; }
        public Nullable<System.DateTime> fldDateRequired { get; set; }
        public bool fldRelationshipCircle { get; set; }
        public bool fldThreeMonthReview { get; set; }
        public bool fldHealthCareReview { get; set; }
        public bool fldClientRisk { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldGoalId { get; set; }
        public Nullable<int> fldStatusSelect { get; set; }
        public Nullable<System.Guid> fldParty { get; set; }
    }
}
