//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFirstContactRiskAssessmentHistory
    {
        public System.Guid fldFirstContactRiskAssessmentHistoryID { get; set; }
        public System.Guid fldFirstContactRiskAssessmentID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public string fldAccessRuralRoad { get; set; }
        public string fldAccessRuralProperty { get; set; }
        public string fldAccessRuralAddressed { get; set; }
        public string fldAccessRuralMobilePhone { get; set; }
        public string fldAccessRuralElectricFence { get; set; }
        public string fldAccessRuralIdentifyingFeatures { get; set; }
        public string fldAccessRuralParking { get; set; }
        public string fldAccessCityNumbers { get; set; }
        public string fldAccessCityProperty { get; set; }
        public string fldAccessCityUnits { get; set; }
        public string fldAccessCityIdentifyingFeatures { get; set; }
        public string fldAccessCityParking { get; set; }
        public Nullable<int> fldRiskSomeonePresent { get; set; }
        public string fldRiskSomeonePresentComments { get; set; }
        public Nullable<int> fldRiskPets { get; set; }
        public string fldRiskPetsComments { get; set; }
        public Nullable<int> fldRiskGuns { get; set; }
        public string fldRiskGunsComments { get; set; }
        public Nullable<int> fldRiskUnwell { get; set; }
        public string fldRiskUnwellComments { get; set; }
        public Nullable<int> fldRiskSmoking { get; set; }
        public string fldRiskSmokingComments { get; set; }
        public string fldOtherServices { get; set; }
        public Nullable<int> fldIssueHomeVisited { get; set; }
        public string fldIssueHomeVisitedComments { get; set; }
        public Nullable<int> fldIssueRisk { get; set; }
        public string fldIssueRiskComments { get; set; }
        public Nullable<int> fldIssueDomestic { get; set; }
        public string fldIssueDomesticComments { get; set; }
        public Nullable<int> fldIssueSubstanceAbuse { get; set; }
        public string fldIssueSubstanceAbuseComments { get; set; }
        public Nullable<int> fldIssueMentalHealth { get; set; }
        public string fldIssueMentalHealthComments { get; set; }
        public Nullable<int> fldIssueChildProtection { get; set; }
        public string fldIssueChildProtectionComments { get; set; }
        public Nullable<int> fldIssueCriminal { get; set; }
        public string fldIssueCriminalComments { get; set; }
        public string fldIssueComments { get; set; }
        public bool fldVisitProceed { get; set; }
        public bool fldSecondPerson { get; set; }
        public string fldIdentifiedNeeds { get; set; }
    }
}
