//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFRCSessionDetail
    {
        public System.Guid fldID { get; set; }
        public string fldActivityCode { get; set; }
        public string fldSessionId { get; set; }
        public string fldOutlet { get; set; }
        public Nullable<System.DateTime> fldSessionDate { get; set; }
        public Nullable<int> fldUnregisteredClients { get; set; }
        public Nullable<System.Guid> fldSubprogram { get; set; }
        public Nullable<System.Guid> fldServiceStrategy { get; set; }
        public Nullable<System.Guid> fldSessionSetting { get; set; }
        public bool fldInterpreterUsed { get; set; }
        public Nullable<decimal> fldFeesCharged { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public bool fldSubmitted { get; set; }
        public Nullable<System.Guid> fldOutletId { get; set; }
        public Nullable<System.Guid> fldActivityId { get; set; }
        public bool fldHasErrors { get; set; }
        public string fldErrorMessage { get; set; }
        public bool fldGroupWork { get; set; }
        public bool fldLegalProfessional { get; set; }
        public int fldSessionReference { get; set; }
        public Nullable<System.Guid> fldCreatedById { get; set; }
        public Nullable<System.Guid> fldRosterShiftId { get; set; }
        public Nullable<int> fldNumberCharged { get; set; }
        public Nullable<int> fldNumberUnableToPay { get; set; }
        public Nullable<int> fldNumberGovernmentExemptions { get; set; }
        public Nullable<int> fldNumberOrganisationExemptions { get; set; }
        public Nullable<int> fldNumberOneHourFree { get; set; }
        public Nullable<int> fldNumberThreeHoursFree { get; set; }
        public Nullable<int> fldNumberFourHoursFree { get; set; }
        public Nullable<int> fldNumberFiveAndSixHoursFree { get; set; }
    }
}
