//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFundingCancellationReason
    {
        public System.Guid fldID { get; set; }
        public string fldCancellationReason { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldEdit { get; set; }
        public bool fldCACPReport { get; set; }
        public string fldCACPCode { get; set; }
        public bool fldEACHReport { get; set; }
        public string fldEACHCode { get; set; }
        public bool fldDisabilityAgeingInPlaceReport { get; set; }
        public string fldDisabilityAgeingInPlaceCode { get; set; }
        public bool fldCDCReport { get; set; }
        public string fldCDCCode { get; set; }
        public Nullable<int> fldComPacksCode { get; set; }
        public string fldExportCode { get; set; }
        public bool fldHCPReport { get; set; }
        public string fldHCPCode { get; set; }
    }
}
