//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFundingBodyHistory
    {
        public System.Guid fldFundingBodyIDHistoryID { get; set; }
        public Nullable<System.Guid> fldFundingBodyID { get; set; }
        public Nullable<System.Guid> fldAddressID { get; set; }
        public Nullable<System.Guid> fldPayRateID { get; set; }
        public string fldStandardDebtorCode { get; set; }
        public string fldProviderNumber { get; set; }
        public Nullable<byte> fldApplyCoPayments { get; set; }
        public Nullable<byte> fldClaimNumber { get; set; }
        public Nullable<byte> fldUseClientBilling { get; set; }
        public Nullable<byte> fldAvailable { get; set; }
        public string fldCostAccount { get; set; }
        public string fldExportCode { get; set; }
        public Nullable<System.Guid> fldFundingBodyGroupID { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public Nullable<System.Guid> fldScheduleID { get; set; }
        public string fldProjectCode { get; set; }
        public Nullable<System.Guid> fldCostScheduleID { get; set; }
    }
}
