//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFundingPackageLeave
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldFundingPackageID { get; set; }
        public Nullable<System.Guid> fldLeaveTypeID { get; set; }
        public Nullable<System.DateTime> fldStartDate { get; set; }
        public Nullable<System.DateTime> fldEndDate { get; set; }
        public Nullable<int> fldEntitlement { get; set; }
        public bool fldConsecutive { get; set; }
        public Nullable<int> fldFreeDays { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<int> fldMaxConsecutive { get; set; }
        public bool fldOvernightOnly { get; set; }
    }
}
