//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFRCReferralTakeup
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldPersonId { get; set; }
        public string fldClientCode { get; set; }
        public string fldActivityCode { get; set; }
        public Nullable<System.DateTime> fldReferralDate { get; set; }
        public Nullable<System.DateTime> fldFollowUpDate { get; set; }
        public Nullable<System.DateTime> fldTakeUpDate { get; set; }
        public Nullable<System.DateTime> fldAvailableDate { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public bool fldSubmitted { get; set; }
        public Nullable<System.Guid> fldActivityId { get; set; }
        public bool fldHasErrors { get; set; }
        public string fldErrorMessage { get; set; }
        public Nullable<System.Guid> fldCreatedById { get; set; }
        public int fldFRSPId { get; set; }
        public Nullable<System.Guid> fldFRCReferralId { get; set; }
    }
}
