//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFRCRegistration
    {
        public System.Guid fldID { get; set; }
        public string fldMothersMaidenName { get; set; }
        public Nullable<int> fldArrivalYear { get; set; }
        public Nullable<System.Guid> fldPractitionerGenderPreference { get; set; }
        public bool fldConfidentiality1 { get; set; }
        public bool fldConfidentiality2 { get; set; }
        public bool fldConfidentiality3 { get; set; }
        public bool fldConfidentiality4 { get; set; }
        public bool fldConfidentiality5 { get; set; }
        public bool fldConfidentiality6 { get; set; }
        public bool fldConfidentiality7 { get; set; }
        public bool fldDisabilityNeeds1 { get; set; }
        public bool fldDisabilityNeeds2 { get; set; }
        public bool fldDisabilityNeeds3 { get; set; }
        public bool fldDisabilityNeeds4 { get; set; }
        public bool fldDisabilityNeeds5 { get; set; }
        public bool fldDayPrefMon { get; set; }
        public bool fldDayPrefTues { get; set; }
        public bool fldDayPrefWed { get; set; }
        public bool fldDayPrefThur { get; set; }
        public bool fldDayPrefFri { get; set; }
        public bool fldTimePrefDay { get; set; }
        public bool fldTimePrefLunch { get; set; }
        public bool fldTimePrefAH { get; set; }
        public bool fldTimePrefAny { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonId { get; set; }
        public Nullable<System.Guid> fldEnglishAbility { get; set; }
        public int fldFRSPClientId { get; set; }
        public bool fldSubmitted { get; set; }
        public bool fldHasErrors { get; set; }
        public string fldErrorMessage { get; set; }
        public string fldSLK { get; set; }
        public Nullable<System.Guid> fldCreatedById { get; set; }
        public Nullable<System.DateTime> fldRegistrationDate { get; set; }
    }
}
