//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrandparentsMain
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldTitleID { get; set; }
        public string fldFirstName { get; set; }
        public string fldLastName { get; set; }
        public string fldClientNumber { get; set; }
        public string fldStreetAddress { get; set; }
        public Nullable<System.Guid> fldSuburb { get; set; }
        public string fldPostalStreetAddress { get; set; }
        public Nullable<System.Guid> fldPostalSuburb { get; set; }
        public string fldHomePhone { get; set; }
        public string fldWorkPhone { get; set; }
        public string fldMobilePhone { get; set; }
        public string fldEmailAddress { get; set; }
        public Nullable<System.DateTime> fldDateOfFirstContact { get; set; }
        public Nullable<int> fldNumberDependentChildren { get; set; }
        public string fldIndigenousStatusOther { get; set; }
        public Nullable<System.Guid> fldMaritalStatus { get; set; }
        public Nullable<System.Guid> fldFinancialStatus { get; set; }
        public string fldAdditionalDetails { get; set; }
        public bool fldAccessToTransport { get; set; }
        public bool fldTransportType { get; set; }
        public bool fldPreviouslyAccessed { get; set; }
        public bool fldSEL { get; set; }
        public bool fldCGA { get; set; }
        public bool fldDCS { get; set; }
        public bool fldDeptCommunities { get; set; }
        public bool fldCSA { get; set; }
        public bool fldDSQ { get; set; }
        public bool fldEducationalAgency { get; set; }
        public bool fldFamily { get; set; }
        public bool fldHealthAgency { get; set; }
        public bool fldLocalGovernment { get; set; }
        public bool fldQPS { get; set; }
        public bool fldQldHealth { get; set; }
        public bool fldReferralOther { get; set; }
        public string fldReferralOtherText { get; set; }
        public bool fldSelf { get; set; }
        public bool fldGSG { get; set; }
        public bool fldCentrelink { get; set; }
        public bool fldCentrelinkOther { get; set; }
        public string fldCentrelinkText { get; set; }
        public string fldDCSAreaOffice { get; set; }
        public string fldDeptCommunitiesAreaOffice { get; set; }
        public bool fldDeptHousing { get; set; }
        public bool fldMedicalPractitioner { get; set; }
        public bool fldEmploymentAgency { get; set; }
        public bool fldFriend { get; set; }
        public bool fldLegalAgency { get; set; }
        public bool fldEducationQld { get; set; }
        public bool fldSchool { get; set; }
        public string fldSelfText { get; set; }
        public string fldOfficerName { get; set; }
        public Nullable<System.DateTime> fldOfficerDate { get; set; }
        public string fldOfficerPhone { get; set; }
        public string fldOfficerEmail { get; set; }
        public string fldDataEntryName { get; set; }
        public Nullable<System.DateTime> fldDataEntryDate { get; set; }
        public string fldDataEntryPhone { get; set; }
        public string fldDataEntryEmail { get; set; }
        public Nullable<int> fldCarerWellbeingPrimaryFactor { get; set; }
        public bool fldChildMentalHealth { get; set; }
        public bool fldChildBehaviour { get; set; }
        public bool fldChildLearning { get; set; }
        public bool fldChildGrief { get; set; }
        public bool fldChildHealth { get; set; }
        public bool fldChildConflict { get; set; }
        public bool fldLackSocialSupport { get; set; }
        public bool fldLackSupportServices { get; set; }
        public bool fldSocialIsolation { get; set; }
        public bool fldIllHealth { get; set; }
        public bool fldAgeRelated { get; set; }
        public bool fldParentingRole { get; set; }
        public bool fldLackAccommodation { get; set; }
        public bool fldFinancialDifficulties { get; set; }
        public bool fldSocialCultural { get; set; }
        public bool fldStress { get; set; }
        public bool fldCarerBurnout { get; set; }
        public bool fldDepression { get; set; }
        public bool fldCaringPartner { get; set; }
        public bool fldLosingChildren { get; set; }
        public bool fldLegalStatus { get; set; }
        public bool fldStatutorySystem { get; set; }
        public bool fldThreatenedViolence { get; set; }
        public bool fldDrugAddiction { get; set; }
        public bool fldChildViolence { get; set; }
        public bool fldOtherFactors { get; set; }
        public bool fldReferredToSupportServices { get; set; }
        public string fldReferralDetails { get; set; }
        public Nullable<int> fldEligibility { get; set; }
        public bool fldVerbalConsent { get; set; }
        public Nullable<System.DateTime> fldDateOfConsent { get; set; }
        public bool fldClientQuestionnaire { get; set; }
        public bool fldChildQuestionnaire { get; set; }
        public bool fldCarerTime { get; set; }
        public bool fldCarerPeerSupport { get; set; }
        public bool fldCarerAnxiety { get; set; }
        public bool fldCarerRoutine { get; set; }
        public bool fldCarerActivities { get; set; }
        public bool fldCarerDevelopment { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldOfficerID { get; set; }
        public Nullable<System.Guid> fldDataEntryID { get; set; }
        public Nullable<System.DateTime> fldVerbalConsentDate { get; set; }
        public Nullable<System.DateTime> fldClosureDate { get; set; }
        public Nullable<System.Guid> fldClosedBy { get; set; }
        public Nullable<System.Guid> fldClosureReason { get; set; }
    }
}
