//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroup
    {
        public tblGroup()
        {
            this.tblPermissions = new HashSet<tblPermission>();
        }
    
        public System.Guid fldId { get; set; }
        public string fldGroupName { get; set; }
    
        public virtual ICollection<tblPermission> tblPermissions { get; set; }
    }
}
