//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHasiSupportPackageDetail
    {
        public System.Guid fldHASISupportPackageDetailsId { get; set; }
        public Nullable<System.Guid> fldPersonId { get; set; }
        public Nullable<System.Guid> fldHasiSupportPackageId { get; set; }
        public string fldPackageNumber { get; set; }
        public Nullable<System.DateTime> fldStartDate { get; set; }
        public bool fldForm1Package { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
    }
}
