//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblINIInitialActionPlanHistory
    {
        public System.Guid fldDateHistoryID { get; set; }
        public Nullable<System.DateTime> fldDate { get; set; }
        public string fldFor { get; set; }
        public Nullable<System.Guid> fldID { get; set; }
        public Nullable<System.Guid> fldINIID { get; set; }
        public string fldAgencyProfessional { get; set; }
        public string fldConsumerConsent { get; set; }
        public string fldReferralMethod { get; set; }
        public string fldFeedbackRequired { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public string fldPhone { get; set; }
        public string fldPurpose { get; set; }
        public Nullable<System.Guid> fldService { get; set; }
        public string fldTransportMethod { get; set; }
        public Nullable<System.DateTime> fldReviewDate { get; set; }
    }
}
