//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblINIInformationExchange
    {
        public System.Guid fldID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldINIID { get; set; }
        public string fldRole { get; set; }
        public string fldName { get; set; }
        public string fldOrganisation { get; set; }
        public string fldEmail { get; set; }
        public string fldPosition { get; set; }
        public string fldPhone { get; set; }
        public string fldFax { get; set; }
        public bool fldFeedbackAfterAssessment { get; set; }
        public Nullable<System.DateTime> fldAssessmentDate { get; set; }
        public bool fldAssessmentAttached { get; set; }
        public bool fldInformationAttached { get; set; }
        public int fldRisks { get; set; }
        public bool fldFeedbackNoteType { get; set; }
        public string fldFeedbackNotes { get; set; }
        public bool fldSharedInformation { get; set; }
        public bool fldSpecificGoals { get; set; }
        public bool fldCarePlanAttached { get; set; }
        public Nullable<System.DateTime> fldCarePlanDate { get; set; }
        public string fldServiceDuration { get; set; }
        public Nullable<System.DateTime> fldPlannedReviewDate { get; set; }
        public Nullable<System.DateTime> fldPlannedReviewDate2 { get; set; }
        public bool fldCarePlanNoteType { get; set; }
        public string fldCarePlanNotes { get; set; }
        public bool fldReviewPlan { get; set; }
        public Nullable<System.DateTime> fldReviewDate { get; set; }
        public bool fldReviewReason { get; set; }
        public bool fldUpdatedPlanAttached { get; set; }
        public bool fldReviewPlanNoteType { get; set; }
        public string fldReviewPlanNotes { get; set; }
        public bool fldHandover { get; set; }
        public bool fldCourseCompleted { get; set; }
        public Nullable<int> fldGoalsAchieved { get; set; }
        public Nullable<System.DateTime> fldTransitionDate { get; set; }
        public Nullable<System.DateTime> fldDischargeDate { get; set; }
        public bool fldHandoverNoteType { get; set; }
        public string fldHandoverNotes { get; set; }
    }
}
