//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblINIMasterHistory
    {
        public System.Guid fldCOBAustraliaOtherHistoryID { get; set; }
        public Nullable<int> fldCOBAustraliaOther { get; set; }
        public Nullable<bool> fldConsumerConsent2a { get; set; }
        public Nullable<bool> fldConsumerConsent2b { get; set; }
        public Nullable<bool> fldConsumerPrivacy { get; set; }
        public Nullable<System.DateTime> fldDate2a { get; set; }
        public Nullable<System.DateTime> fldDate2b { get; set; }
        public Nullable<bool> fldDiscuss1 { get; set; }
        public Nullable<bool> fldDiscuss2 { get; set; }
        public Nullable<bool> fldDiscuss3 { get; set; }
        public Nullable<bool> fldDiscuss4 { get; set; }
        public string fldHealthCareCardNumber { get; set; }
        public string fldInsuranceCardNumber { get; set; }
        public string fldInsurerName { get; set; }
        public Nullable<System.DateTime> fldLastUpdated { get; set; }
        public string fldMedicareNumber { get; set; }
        public string fldNotesReasonSeekService { get; set; }
        public string fldPractitionerName2a { get; set; }
        public string fldPractitionerName2b { get; set; }
        public string fldPreferredLanguage { get; set; }
        public string fldReasonSeekService { get; set; }
        public string fldRole2a { get; set; }
        public string fldRole2b { get; set; }
        public string fldServiceRequested { get; set; }
        public string fldServiceRequestedNotes { get; set; }
        public string fldWitnessed2a { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldID { get; set; }
        public Nullable<System.Guid> fldPensionStatus { get; set; }
        public Nullable<System.Guid> fldReferralSource { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public string fldInterpreterRequired { get; set; }
        public Nullable<System.Guid> fldContactAddress { get; set; }
        public Nullable<System.Guid> fldUsualAddress { get; set; }
        public Nullable<int> fldMainLanguage { get; set; }
        public string fldMedicationComments { get; set; }
        public Nullable<int> fldPageCompletedBy { get; set; }
        public Nullable<System.Guid> fldReferralRelationship { get; set; }
        public Nullable<System.Guid> fldReferralOrganisation { get; set; }
        public Nullable<bool> fldClientConsent { get; set; }
        public string fldPriorityRating { get; set; }
        public Nullable<int> fldHACCEligible { get; set; }
        public Nullable<int> fldStatusReason { get; set; }
        public Nullable<int> fldDisabilityEligible { get; set; }
        public Nullable<bool> fldSupportEligible { get; set; }
        public string fldSupportEligibleText { get; set; }
        public Nullable<bool> fldFunctionalProfileCompleted { get; set; }
        public string fldMedicationReminding { get; set; }
        public string fldMedicationPrescribed { get; set; }
        public string fldCooperateHealth { get; set; }
        public Nullable<bool> fldWebsterPack { get; set; }
        public Nullable<bool> fldReviewMedications { get; set; }
        public string fldLostWeight { get; set; }
        public Nullable<int> fldLostWeightScore { get; set; }
        public string fldWeightLoss { get; set; }
        public Nullable<int> fldWeightLossScore { get; set; }
        public string fldDecreasedAppetite { get; set; }
        public Nullable<int> fldDecreasedAppetiteScore { get; set; }
        public Nullable<bool> fldHydration { get; set; }
        public Nullable<bool> fldDecreasedFluid { get; set; }
        public Nullable<int> fldWeight { get; set; }
        public Nullable<bool> fldHealthChecks { get; set; }
        public string fldHealthCheckComments { get; set; }
        public Nullable<bool> fldIsCarer { get; set; }
        public string fldHistory { get; set; }
        public string fldMedications { get; set; }
        public string fldAllergies { get; set; }
        public string fldRisks { get; set; }
        public string fldAdditionalComments { get; set; }
        public Nullable<bool> fldDateOfBirthEstimated { get; set; }
        public string fldCommunicationMethod { get; set; }
        public string fldHealthCareCardHolderStatus { get; set; }
        public string fldCompensablesSource { get; set; }
        public string fldConsumerComments { get; set; }
        public string fldCompletedByName { get; set; }
        public string fldCompletedByAgency { get; set; }
        public Nullable<bool> fldCoresidentCarer { get; set; }
        public Nullable<System.DateTime> fldDateCaringCommenced { get; set; }
        public Nullable<System.DateTime> fldCompletedDate { get; set; }
        public string fldConsentName { get; set; }
        public bool fldAdvised { get; set; }
        public Nullable<System.Guid> fldLegalOrders { get; set; }
        public Nullable<System.DateTime> fldDateWitnessed { get; set; }
        public int fldRatingTool { get; set; }
    }
}
