//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIncident
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldIncidentTypeID { get; set; }
        public bool fldMedicalAttention { get; set; }
        public Nullable<int> fldVictim { get; set; }
        public string fldIncidentTypeOther { get; set; }
        public Nullable<int> fldCategory { get; set; }
        public Nullable<System.Guid> fldRegionID { get; set; }
        public string fldRegionOther { get; set; }
        public Nullable<int> fldReferenceNumber { get; set; }
        public Nullable<System.Guid> fldSiteID { get; set; }
        public string fldFacilityID { get; set; }
        public string fldCostCentreCode { get; set; }
        public string fldReportingOfficer { get; set; }
        public string fldReportingOfficerPhone { get; set; }
        public string fldReportingOfficerPosition { get; set; }
        public Nullable<System.Guid> fldProgramID { get; set; }
        public Nullable<System.DateTime> fldReportDate { get; set; }
        public Nullable<System.DateTime> fldReportTime { get; set; }
        public Nullable<System.DateTime> fldIncidentDate { get; set; }
        public Nullable<System.DateTime> fldIncidentTime { get; set; }
        public string fldIncidentLocation { get; set; }
        public string fldIncidentDescription { get; set; }
        public bool fldEquipmentDamaged { get; set; }
        public string fldDamageDetails { get; set; }
        public string fldFurtherAction { get; set; }
        public string fldActionPlanned { get; set; }
        public string fldMediaResponse { get; set; }
        public string fldSupervisorName { get; set; }
        public string fldSupervisorPhone { get; set; }
        public bool fldCEOInformed { get; set; }
        public Nullable<System.DateTime> fldCEOInformedDate { get; set; }
        public Nullable<System.DateTime> fldCEOInformedTime { get; set; }
        public bool fldPoliceContacted { get; set; }
        public Nullable<System.DateTime> fldPoliceContactedDate { get; set; }
        public Nullable<System.DateTime> fldPoliceContactedTime { get; set; }
        public string fldPoliceOfficerName { get; set; }
        public string fldPoliceOfficerNumber { get; set; }
        public string fldPoliceOfficerPhone { get; set; }
        public bool fldPoliceInvestigation { get; set; }
        public bool fldDINMACompleted { get; set; }
        public bool fldWorkSafeNotified { get; set; }
        public Nullable<System.DateTime> fldPoliceInvestigationDate { get; set; }
        public Nullable<System.DateTime> fldDINMACompletedDate { get; set; }
        public Nullable<System.DateTime> fldWorkSafeNotifiedDate { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public string fldImmediateResponse { get; set; }
        public Nullable<System.Guid> fldDrugId { get; set; }
        public Nullable<int> fldAssaultPerpetratorType { get; set; }
        public Nullable<int> fldAssaultVictimType { get; set; }
        public Nullable<bool> fldAbuseInCare { get; set; }
        public Nullable<bool> fldAbuseInvestigationInitiated { get; set; }
        public Nullable<System.DateTime> fldAbuseInvestigationInitiatedDate { get; set; }
        public Nullable<bool> fldAbuseSafetyNeedsMet { get; set; }
        public string fldAbuseDetails { get; set; }
        public Nullable<bool> fldCASASupportOffered { get; set; }
        public Nullable<bool> fldCASASupportAccepted { get; set; }
        public Nullable<bool> fldCoronerContacted { get; set; }
        public Nullable<System.DateTime> fldCoronerContactedDate { get; set; }
        public Nullable<System.DateTime> fldDateTold { get; set; }
        public Nullable<System.DateTime> fldTimeTold { get; set; }
        public Nullable<System.Guid> fldReportingProgram { get; set; }
        public bool fldInvolvingClient { get; set; }
        public bool fldInvolvingStaff { get; set; }
        public bool fldInvolvingVolunteers { get; set; }
        public bool fldInvolvingStudents { get; set; }
        public bool fldInvolvingOther { get; set; }
        public Nullable<int> fldDebriefingOffered { get; set; }
        public string fldPoliceReportNo { get; set; }
        public bool fldDebriefingAccepted { get; set; }
        public Nullable<System.Guid> fldFacilityDHSProgram { get; set; }
        public Nullable<System.Guid> fldOfficer { get; set; }
        public Nullable<System.Guid> fldPosition { get; set; }
        public bool fldLineManagerInformed { get; set; }
        public Nullable<System.DateTime> fldLineManagerDate { get; set; }
        public Nullable<System.DateTime> fldLineManagerTime { get; set; }
        public bool fldCompulsoryTreatmentOrder { get; set; }
        public string fldManagerPrintName { get; set; }
        public string fldManagerTelephone { get; set; }
        public string fldManagerPosition { get; set; }
        public string fldIncidentSummary { get; set; }
        public bool fldCASASupportOfferedNA { get; set; }
        public bool fldLineManagerInformedNA { get; set; }
        public bool fldPoliceContactedNA { get; set; }
        public bool fldPoliceInvestigationNA { get; set; }
        public bool fldWorkSafeNotifiedNA { get; set; }
        public bool fldReportQualityChecked { get; set; }
        public string fldCoronerCaseNumber { get; set; }
        public Nullable<System.Guid> fldLinkedFacilityID { get; set; }
        public string fldTypeOfServiceProvided { get; set; }
        public Nullable<System.DateTime> fldDateLastContact { get; set; }
        public bool fldIncidentReportChecked { get; set; }
        public Nullable<System.DateTime> fldIncidentReportCheckedDate { get; set; }
        public bool fldConsentByClientProvided { get; set; }
        public bool fldConsentByStaffProvided { get; set; }
    }
}
