//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblINIProfileFunctional
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldINIID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<bool> fldFunctionalDomestic { get; set; }
        public Nullable<bool> fldFunctionalPersonal { get; set; }
        public Nullable<bool> fldFunctionalMobility { get; set; }
        public Nullable<bool> fldFunctionalTransport { get; set; }
        public Nullable<bool> fldFunctionalOther { get; set; }
        public Nullable<bool> fldFunctionalCognition { get; set; }
        public Nullable<bool> fldFunctionalBehaviours { get; set; }
        public string fldFunctionalDomesticComments { get; set; }
        public string fldFunctionalPersonalComments { get; set; }
        public string fldFunctionalMobilityComments { get; set; }
        public string fldFunctionalTransportComments { get; set; }
        public string fldFunctionalOtherComments { get; set; }
        public string fldFunctionalCognitionComments { get; set; }
        public string fldFunctionalBehavioursComments { get; set; }
        public string fldReferralRecommended { get; set; }
        public Nullable<bool> fldFunctionalCommunication { get; set; }
        public string fldFunctionalCommunicationComments { get; set; }
        public bool fldNFAVisionGlasses { get; set; }
        public bool fldNFAVisionActivities { get; set; }
        public string fldNFAVisionComments { get; set; }
    }
}
