//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblINIFamilySocialNetwork
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldINIID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<int> fldType { get; set; }
        public string fldName { get; set; }
        public Nullable<int> fldGender { get; set; }
        public Nullable<System.DateTime> fldDOB { get; set; }
        public Nullable<System.Guid> fldRelationshipType { get; set; }
        public string fldRelationshipAlert { get; set; }
        public bool fldLivesIn { get; set; }
        public string fldAddressContact { get; set; }
        public Nullable<System.Guid> fldLivesInHomeId { get; set; }
        public Nullable<System.Guid> fldEmploymentStatusId { get; set; }
        public bool fldEmergencyCarePlan { get; set; }
    }
}
