//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKeyRegister
    {
        public System.Guid fldKeyRegisterId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonId { get; set; }
        public Nullable<System.Guid> fldKeyLocation { get; set; }
        public Nullable<System.Guid> fldKeyType { get; set; }
        public string fldSerialNumber { get; set; }
        public Nullable<System.DateTime> fldIssueDate { get; set; }
        public Nullable<System.DateTime> fldReplacedDate { get; set; }
        public Nullable<System.DateTime> fldReturnDate { get; set; }
        public string fldDescription { get; set; }
    }
}
