//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogSession
    {
        public System.Guid fldID { get; set; }
        public System.DateTime fldTimestamp { get; set; }
        public string fldApplication { get; set; }
        public string fldMachine { get; set; }
        public byte[] fldData { get; set; }
    }
}
