//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMobileUnit
    {
        public System.Guid fldMobileUnitID { get; set; }
        public string fldIdentifier { get; set; }
        public System.Guid fldMobileUnitTypeID { get; set; }
        public Nullable<System.DateTime> fldPurchasedDate { get; set; }
        public string fldSerialNo { get; set; }
        public Nullable<System.Guid> fldUserID { get; set; }
        public Nullable<bool> fldAccessBlocked { get; set; }
        public Nullable<System.DateTime> fldAccessBlockedDate { get; set; }
        public string fldAccessBlockedReason { get; set; }
        public Nullable<bool> fldInactive { get; set; }
        public Nullable<System.DateTime> fldInactiveDate { get; set; }
        public string fldInactiveReason { get; set; }
        public string fldNotes { get; set; }
        public Nullable<System.Guid> fldStatus { get; set; }
    }
}
