//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMobileUnitsMessageLog
    {
        public System.Guid fldMobileUnitMessageLogID { get; set; }
        public Nullable<System.Guid> fldUserID { get; set; }
        public Nullable<System.DateTime> fldDateTime { get; set; }
        public string fldMessage { get; set; }
        public Nullable<System.Guid> fldMobileUnitID { get; set; }
        public Nullable<int> fldMessageType { get; set; }
        public Nullable<System.DateTime> fldDataDate { get; set; }
    }
}
