//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMDSIndigenousStatu
    {
        public System.Guid fldID { get; set; }
        public Nullable<int> fldCode { get; set; }
        public string fldIndigenousStatus { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldEdit { get; set; }
        public int fldFRCCode { get; set; }
        public string fldHASICode { get; set; }
        public string fldDEEWRCode { get; set; }
        public Nullable<int> fldQDCCode { get; set; }
        public Nullable<int> fldComPacksCode { get; set; }
        public Nullable<int> fldSHSCode { get; set; }
        public string fldFACESCode { get; set; }
        public Nullable<int> fldACDCCode { get; set; }
        public Nullable<int> fldINICode { get; set; }
    }
}
