//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedicalCondition
    {
        public System.Guid fldMedicalConditionsID { get; set; }
        public System.Guid fldMedicalConditionTypeID { get; set; }
        public System.Guid fldClientID { get; set; }
        public Nullable<System.DateTime> fldDateOfAccident { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public string fldMedicationName { get; set; }
        public string fldDosage { get; set; }
        public string fldAdministrationTimes { get; set; }
        public Nullable<System.Guid> fldDiagnosedBy { get; set; }
        public string fldSymptoms { get; set; }
        public string fldTriggers { get; set; }
        public string fldTreatment { get; set; }
    }
}
