//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMDSNSWAllied
    {
        public System.Guid fldID { get; set; }
        public Nullable<int> fldAlliedHealthType { get; set; }
        public Nullable<double> AtHomeTotal { get; set; }
        public Nullable<double> AtCentreTotal { get; set; }
        public Nullable<System.Guid> fldUserID { get; set; }
        public Nullable<System.Guid> fldClientID { get; set; }
    }
}
