//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMDSActivityCombo
    {
        public System.Guid fldID { get; set; }
        public string fldText { get; set; }
        public Nullable<int> fldCode { get; set; }
        public Nullable<int> fldQuestion { get; set; }
    }
}
