//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaintenanceRecord
    {
        public System.Guid fldID { get; set; }
        public string fldCheck1 { get; set; }
        public string fldCheck2 { get; set; }
        public string fldCheck3 { get; set; }
        public string fldCheck4 { get; set; }
        public Nullable<System.Guid> fldForeignId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public string fldCheck5 { get; set; }
        public Nullable<System.DateTime> fldDateCheck1 { get; set; }
    }
}
