//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMobileShiftsCompleted
    {
        public System.Guid fldRosterShiftId { get; set; }
        public System.DateTime fldActualStartTime { get; set; }
        public System.DateTime fldActualEndTime { get; set; }
        public Nullable<decimal> fldExpenses { get; set; }
        public Nullable<decimal> fldTravelDistance { get; set; }
        public Nullable<decimal> fldTravelDistanceInt { get; set; }
        public Nullable<short> fldTravelTime { get; set; }
        public byte[] fldClientSignature { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public Nullable<int> fldStatusCode { get; set; }
        public System.Guid fldMobileShiftsCompletedId { get; set; }
        public Nullable<System.Guid> fldCarerId { get; set; }
    }
}
