//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedicareOnlineSetup
    {
        public System.Guid fldID { get; set; }
        public string fldLocationId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldEdit { get; set; }
        public string fldServer { get; set; }
        public string fldRecipient { get; set; }
        public string fldPMSClaimId { get; set; }
        public string fldFileLocation { get; set; }
        public string fldPSIPass { get; set; }
        public string fldTokenPass { get; set; }
        public string fldSender { get; set; }
    }
}
