//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNCFA
    {
        public System.Guid fldID { get; set; }
        public Nullable<int> fldEnvironment1 { get; set; }
        public Nullable<int> fldEnvironment2 { get; set; }
        public Nullable<int> fldEnvironment3 { get; set; }
        public Nullable<int> fldEnvironment4 { get; set; }
        public Nullable<int> fldEnvironment5 { get; set; }
        public Nullable<int> fldEnvironment6 { get; set; }
        public Nullable<int> fldEnvironment7 { get; set; }
        public Nullable<int> fldParenting1 { get; set; }
        public Nullable<int> fldParenting2 { get; set; }
        public Nullable<int> fldParenting3 { get; set; }
        public Nullable<int> fldParenting4 { get; set; }
        public Nullable<int> fldParenting5 { get; set; }
        public Nullable<int> fldParenting6 { get; set; }
        public Nullable<int> fldParenting7 { get; set; }
        public Nullable<int> fldParenting8 { get; set; }
        public Nullable<int> fldFamily1 { get; set; }
        public Nullable<int> fldFamily2 { get; set; }
        public Nullable<int> fldFamily3 { get; set; }
        public Nullable<int> fldFamily4 { get; set; }
        public Nullable<int> fldFamily5 { get; set; }
        public Nullable<int> fldFamily6 { get; set; }
        public Nullable<int> fldFamily7 { get; set; }
        public Nullable<int> fldFamily8 { get; set; }
        public Nullable<int> fldSafety1 { get; set; }
        public Nullable<int> fldSafety2 { get; set; }
        public Nullable<int> fldSafety3 { get; set; }
        public Nullable<int> fldSafety4 { get; set; }
        public Nullable<int> fldSafety5 { get; set; }
        public Nullable<int> fldSafety6 { get; set; }
        public Nullable<int> fldSafety7 { get; set; }
        public Nullable<int> fldSafety8 { get; set; }
        public Nullable<int> fldWellbeing1 { get; set; }
        public Nullable<int> fldWellbeing2 { get; set; }
        public Nullable<int> fldWellbeing3 { get; set; }
        public Nullable<int> fldWellbeing4 { get; set; }
        public Nullable<int> fldWellbeing5 { get; set; }
        public Nullable<int> fldWellbeing6 { get; set; }
        public Nullable<int> fldWellbeing7 { get; set; }
        public Nullable<int> fldSocial1 { get; set; }
        public Nullable<int> fldSocial2 { get; set; }
        public Nullable<int> fldSocial3 { get; set; }
        public Nullable<int> fldSocial4 { get; set; }
        public Nullable<int> fldSocial5 { get; set; }
        public Nullable<int> fldSocial6 { get; set; }
        public Nullable<int> fldSelfSufficiency1 { get; set; }
        public Nullable<int> fldSelfSufficiency2 { get; set; }
        public Nullable<int> fldSelfSufficiency3 { get; set; }
        public Nullable<int> fldSelfSufficiency4 { get; set; }
        public Nullable<int> fldSelfSufficiency5 { get; set; }
        public Nullable<int> fldSelfSufficiency6 { get; set; }
        public Nullable<int> fldHealth1 { get; set; }
        public Nullable<int> fldHealth2 { get; set; }
        public Nullable<int> fldHealth3 { get; set; }
        public Nullable<int> fldHealth4 { get; set; }
        public Nullable<int> fldHealth5 { get; set; }
        public Nullable<int> fldHealth6 { get; set; }
        public Nullable<int> fldHealth7 { get; set; }
        public Nullable<int> fldHealth8 { get; set; }
        public Nullable<int> fldAmbivalence1 { get; set; }
        public Nullable<int> fldAmbivalence2 { get; set; }
        public Nullable<int> fldAmbivalence3 { get; set; }
        public Nullable<int> fldAmbivalence4 { get; set; }
        public Nullable<int> fldAmbivalence5 { get; set; }
        public Nullable<int> fldAmbivalence6 { get; set; }
        public Nullable<int> fldReadiness1 { get; set; }
        public Nullable<int> fldReadiness2 { get; set; }
        public Nullable<int> fldReadiness3 { get; set; }
        public Nullable<int> fldReadiness4 { get; set; }
        public Nullable<int> fldReadiness5 { get; set; }
        public Nullable<int> fldReadiness6 { get; set; }
        public string fldEnvironmentComments { get; set; }
        public string fldParentingComments { get; set; }
        public string fldFamilyComments { get; set; }
        public string fldSafetyComments { get; set; }
        public string fldWellbeingComments { get; set; }
        public string fldSocialComments { get; set; }
        public string fldSelfSufficiencyComments { get; set; }
        public string fldHealthComments { get; set; }
        public string fldAmbivalenceComments { get; set; }
        public string fldReadinessComments { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
    }
}
