//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblONIN
    {
        public System.Guid fldONINID { get; set; }
        public Nullable<System.Guid> fldAccnaID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public string fldAssessmentPurpose { get; set; }
        public string fldDescriptionProblem { get; set; }
        public string fldOtherIssues { get; set; }
        public string fldContactInstructions { get; set; }
        public byte fldConcessionCard { get; set; }
        public string fldConcessionCardNumber { get; set; }
        public Nullable<System.DateTime> fldConcessionCardExpiry { get; set; }
        public Nullable<System.DateTime> fldHealthCareCardExpiry { get; set; }
        public Nullable<System.DateTime> fldHealthInsurerExpiry { get; set; }
        public string fldInsuranceComments { get; set; }
        public string fldFunctionalComments { get; set; }
        public string fldCaringRoleComments { get; set; }
        public bool fldDementia { get; set; }
        public bool fldDementiaDiagnosis { get; set; }
        public bool fldDementiaCognitive { get; set; }
        public string fldDementiaComments { get; set; }
        public string fldBodilyPaidComments { get; set; }
        public Nullable<int> fldVisionReadingGlasses { get; set; }
        public Nullable<int> fldVisionLongDistanceGlasses { get; set; }
        public string fldVisionComments { get; set; }
        public Nullable<int> fldHearingHearingAid { get; set; }
        public bool fldSpeechHealthProfessional { get; set; }
        public string fldEquipmentComments { get; set; }
        public string fldMedicationSchedule { get; set; }
        public string fldVaccinationFluStatus { get; set; }
        public string fldVaccinationFluBy { get; set; }
        public string fldVaccinationPneumoStatus { get; set; }
        public string fldVaccinationPneumoBy { get; set; }
        public string fldVaccinationTetanusStatus { get; set; }
        public string fldVaccinationTetanusBy { get; set; }
        public string fldVaccinationOtherStatus { get; set; }
        public string fldVaccinationOtherBy { get; set; }
        public string fldVaccinationOther2Status { get; set; }
        public Nullable<System.DateTime> fldVaccinationOther2Date { get; set; }
        public string fldVaccinationOther2By { get; set; }
        public string fldDecisionMakerComments { get; set; }
        public string fldMentalHealthComments { get; set; }
        public bool fldFinancialOther { get; set; }
        public string fldFinancialOtherDetails { get; set; }
        public string fldCareContextType { get; set; }
        public string fldCareContextWho { get; set; }
        public string fldCareContextHowOften { get; set; }
        public Nullable<System.DateTime> fldHealthCheckDate { get; set; }
        public string fldReferralID { get; set; }
        public Nullable<System.DateTime> fldAssessedOnDate { get; set; }
        public Nullable<System.DateTime> fldReferralDate { get; set; }
        public string fldAssessorName { get; set; }
        public string fldAssessorPosition { get; set; }
        public string fldAssessorWorkPhone { get; set; }
        public string fldAssessorFax { get; set; }
        public string fldAssessorEmail { get; set; }
        public bool fldMedication { get; set; }
        public string fldContinenceSeverity { get; set; }
        public bool fldDisclosure { get; set; }
    }
}
