//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblORSSR
    {
        public System.Guid fldORSSRSID { get; set; }
        public Nullable<System.Guid> fldCaseActivityID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public string fldORSIndividually { get; set; }
        public string fldORSInterpersonally { get; set; }
        public string fldORSSocially { get; set; }
        public string fldORSOverall { get; set; }
        public string fldSRSRelationship { get; set; }
        public string fldSRSGoals { get; set; }
        public string fldSRSApproach { get; set; }
        public string fldSRSOverall { get; set; }
        public Nullable<System.Guid> fldOriginalUserId { get; set; }
    }
}
