//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayRate
    {
        public System.Guid fldPayRateID { get; set; }
        public string fldPayRateName { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldEdit { get; set; }
        public string fldPayrateCode { get; set; }
        public bool fldUseForKilometres { get; set; }
        public bool fldUseForExpenses { get; set; }
        public string fldCancellationExportCode { get; set; }
        public string fldTravelTimeCode { get; set; }
        public string fldExportLineType { get; set; }
        public bool fldUseForTravel { get; set; }
        public string fldAlternateCode { get; set; }
        public Nullable<int> fldAccrualPercent { get; set; }
        public bool fldIsOvertime { get; set; }
        public Nullable<decimal> fldMultiplicationRate { get; set; }
        public Nullable<decimal> fldLeaveLoading { get; set; }
        public string fldExportCode { get; set; }
    }
}
