//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPreference
    {
        public System.Guid fldPreferenceID { get; set; }
        public System.Guid fldPersonID { get; set; }
        public System.Guid fldSystemMaintenceID { get; set; }
        public byte fldPattern { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldExclude { get; set; }
        public bool fldBlocked { get; set; }
        public bool fldTrainingRequired { get; set; }
        public Nullable<int> fldLowerAgeLimit { get; set; }
        public Nullable<int> fldUpperAgeLimit { get; set; }
        public bool fldAgeGreaterThan { get; set; }
        public bool fldAgeLessThan { get; set; }
        public bool fldHasMatchPriority { get; set; }
        public bool fldRequestedHours { get; set; }
        public bool fldExtraAvailability { get; set; }
    }
}
