//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPension
    {
        public System.Guid fldPensionID { get; set; }
        public System.Guid fldPersonId { get; set; }
        public Nullable<System.Guid> fldPensionTypeId { get; set; }
        public Nullable<System.DateTime> fldDateTimeStart { get; set; }
        public Nullable<System.DateTime> fldDateTimeEnd { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public string fldPensionNumber { get; set; }
        public Nullable<int> fldMDSPensionStatus { get; set; }
        public Nullable<int> fldMDSCardStatus { get; set; }
        public string fldDVACardNumber { get; set; }
        public Nullable<System.Guid> fldMDSPensionStatusID { get; set; }
        public Nullable<System.Guid> fldMDSCardStatusID { get; set; }
        public string fldPensionBenefitOther { get; set; }
        public string fldDVACardOther { get; set; }
        public Nullable<System.DateTime> fldDVACardExpiry { get; set; }
    }
}
