//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonMembership
    {
        public System.Guid fldPersonMembershipID { get; set; }
        public System.Guid fldMembershipTypeID { get; set; }
        public System.Guid fldPersonID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public string fldMembershipNumber { get; set; }
        public Nullable<System.DateTime> fldRenewalDate { get; set; }
        public byte fldWorkRelatedInjury { get; set; }
        public byte fldAdvocateMailingList { get; set; }
        public byte fldMemberNetworkMailouts { get; set; }
        public Nullable<System.DateTime> fldStartDate { get; set; }
        public Nullable<System.DateTime> fldDeactivationDate { get; set; }
        public Nullable<System.Guid> fldDeactivationReasonId { get; set; }
        public bool fldPrimaryMember { get; set; }
        public Nullable<System.Guid> fldMemberTypeId { get; set; }
        public Nullable<System.Guid> fldMemberAwardId { get; set; }
        public Nullable<System.DateTime> fldMembershipStartDate { get; set; }
        public Nullable<System.DateTime> fldMembershipEndDate { get; set; }
        public Nullable<System.Guid> fldCessationReasonId { get; set; }
    }
}
