//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonRelationShipsHistory
    {
        public System.Guid fldPersonIDHistoryID { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldFieldRelationID { get; set; }
        public Nullable<System.Guid> fldPersonRelationShipTypeID { get; set; }
        public Nullable<byte> fldDefault { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public Nullable<int> fldFirst { get; set; }
        public Nullable<int> fldSecond { get; set; }
        public Nullable<int> fldPrefGP { get; set; }
        public Nullable<int> fldMDSResidencyStatus { get; set; }
        public Nullable<System.Guid> fldID { get; set; }
        public Nullable<byte> fldNOK { get; set; }
        public Nullable<bool> fldConfidential { get; set; }
        public Nullable<bool> fldIsCarer { get; set; }
        public Nullable<System.DateTime> fldDateCareCommenced { get; set; }
        public Nullable<bool> fldRestrictedAccess { get; set; }
        public Nullable<System.DateTime> fldRestrictedStartDate { get; set; }
        public Nullable<System.DateTime> fldRestrictedEndDate { get; set; }
        public bool fldResidesWithClient { get; set; }
        public bool fldLegal { get; set; }
        public bool fldIsDecisionMaker { get; set; }
        public Nullable<System.Guid> fldLivesWithRelationshipID { get; set; }
        public string fldSchoolYear { get; set; }
        public Nullable<System.Guid> fldForeignId { get; set; }
        public Nullable<int> fldThird { get; set; }
        public Nullable<System.Guid> fldOrganisationSiteAddressId { get; set; }
        public string fldDetails { get; set; }
        public string fldDetailsOfSupport { get; set; }
        public Nullable<System.Guid> fldQDCCarerRelationship { get; set; }
        public bool fldIsAuthorisedToTransportClient { get; set; }
        public Nullable<System.DateTime> fldDateLastVisit { get; set; }
        public string fldReasonLastVisit { get; set; }
        public Nullable<System.Guid> fldGPPracticeOrganisationSiteId { get; set; }
    }
}
