//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonEducation
    {
        public System.Guid fldPersonEducationID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldFacilityType { get; set; }
        public Nullable<System.Guid> fldEducationFacilityOrgSiteAddressId { get; set; }
        public string fldYearAtSchool { get; set; }
        public Nullable<System.Guid> fldEducatorSector { get; set; }
        public Nullable<decimal> fldAideTimeAllocated { get; set; }
        public string fldCurrentAttendance { get; set; }
        public Nullable<System.Guid> fldEducationSupportNeeds { get; set; }
        public Nullable<System.Guid> fldPrincipalRelationshipId { get; set; }
        public Nullable<System.Guid> fldTeacherRelationshipId { get; set; }
        public Nullable<System.Guid> fldTeachersAideRelationshipId { get; set; }
        public Nullable<System.Guid> fldLearningSupportCoordinatorRelationshipId { get; set; }
        public Nullable<System.Guid> fldSchoolPsychologistRelationshipId { get; set; }
        public Nullable<System.Guid> fldVisitingConsultantRelationshipId { get; set; }
    }
}
