//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerson
    {
        public tblPerson()
        {
            this.AcpActionItems = new HashSet<AcpActionItem>();
            this.AcpFilledForms = new HashSet<AcpFilledForm>();
            this.AcpFilledFormAttachedPersons = new HashSet<AcpFilledFormAttachedPerson>();
            this.MhcssIndividualClientSupportPackages = new HashSet<MhcssIndividualClientSupportPackage>();
            this.MhcssIntakeAssessments = new HashSet<MhcssIntakeAssessment>();
            this.MhcssYouthResidentialRehabs = new HashSet<MhcssYouthResidentialRehab>();
        }
    
        public System.Guid fldPersonID { get; set; }
        public string fldFirstName { get; set; }
        public string fldLastName { get; set; }
        public string fldOtherNames { get; set; }
        public string fldNamePreference { get; set; }
        public Nullable<System.DateTime> fldDOB { get; set; }
        public System.Guid fldTitleID { get; set; }
        public Nullable<System.Guid> fldGenderId { get; set; }
        public Nullable<System.Guid> fldCultureId { get; set; }
        public Nullable<System.Guid> fldReligionId { get; set; }
        public byte fldFictitious { get; set; }
        public byte fldContractor { get; set; }
        public Nullable<System.Guid> fldCountryOfBirth { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public int fldEziPayID { get; set; }
        public Nullable<System.Guid> fldCategoryID { get; set; }
        public byte fldFacility { get; set; }
        public bool fldEziPayApplies { get; set; }
        public Nullable<System.Guid> fldResidencyStatus { get; set; }
        public Nullable<System.Guid> fldMaritalStatus { get; set; }
        public Nullable<System.Guid> fldEmploymentStatus { get; set; }
        public bool fldIsMDS { get; set; }
        public Nullable<System.Guid> fldDVARegion { get; set; }
        public bool fldDOBEstimated { get; set; }
        public Nullable<System.Guid> fldIndigenousStatusID { get; set; }
        public bool fldExcludeClashes { get; set; }
        public Nullable<System.Guid> fldHouseholdComposition { get; set; }
        public string fldOccupation { get; set; }
        public Nullable<int> fldNoDependents { get; set; }
        public string fldProviderNumber { get; set; }
        public bool fldSilentNumber { get; set; }
        public bool fldNotEzipayCompatible { get; set; }
        public Nullable<System.Guid> fldNotEziPayCompatibleReasonId { get; set; }
        public int fldFlag { get; set; }
        public Nullable<System.Guid> fldDeleteReasonId { get; set; }
        public int fldWorkflowStatus { get; set; }
        public int fldWorkflowHeader { get; set; }
        public string fldWorkflowNotes { get; set; }
        public Nullable<int> fldFAHCSIAId { get; set; }
        public string fldExchangeURI { get; set; }
        public string fldExchangeCarerURI { get; set; }
        public Nullable<System.Guid> fldGPPractice { get; set; }
        public bool fldGTSApplies { get; set; }
        public bool fldSubmitted { get; set; }
        public bool fldLoginReminder { get; set; }
        public string fldPEG { get; set; }
        public string fldMedicare { get; set; }
        public string fldTaxiCard { get; set; }
        public Nullable<System.Guid> fldCurrentCountryID { get; set; }
        public Nullable<int> fldTechOneID { get; set; }
        public string fldTechOneUserID { get; set; }
        public Nullable<System.Guid> fldTelephonyPodID { get; set; }
        public Nullable<System.Guid> fldCSOId { get; set; }
        public bool fldCALD { get; set; }
        public Nullable<System.DateTime> fldYearOfArrival { get; set; }
        public string fldMigrationStatus { get; set; }
        public string fldTribalName { get; set; }
        public Nullable<System.Guid> fldLocalHealthDistrictId { get; set; }
        public Nullable<System.DateTime> fldMedicareExpiry { get; set; }
        public string fldUserDefined1 { get; set; }
        public string fldReligiousConsiderations { get; set; }
        public Nullable<System.Guid> fldDailyOccupation { get; set; }
        public string fldCentrelinkReference { get; set; }
        public Nullable<System.Guid> fldCentrelinkOffice { get; set; }
        public Nullable<System.Guid> fldAgeGroup { get; set; }
        public Nullable<System.Guid> fldFamilyIncome { get; set; }
        public bool fldSoleParent { get; set; }
        public Nullable<System.Guid> fldAssistsInSelfCare { get; set; }
        public Nullable<System.Guid> fldReceiptOfCarerAllowance { get; set; }
        public Nullable<System.Guid> fldOtherStatusId { get; set; }
        public Nullable<System.Guid> fldOtherStatusReasonId { get; set; }
        public Nullable<System.Guid> fldResidencyStatusAsCarer { get; set; }
        public Nullable<System.Guid> fldACDCID { get; set; }
        public bool fldSynchronised { get; set; }
        public bool fldEziPaySynchronised { get; set; }
        public Nullable<System.Guid> fldLivingArrangements { get; set; }
        public Nullable<System.Guid> fldAccommodationSetting { get; set; }
        public string fldCustomPersonId { get; set; }
    
        public virtual ICollection<AcpActionItem> AcpActionItems { get; set; }
        public virtual ICollection<AcpFilledForm> AcpFilledForms { get; set; }
        public virtual ICollection<AcpFilledFormAttachedPerson> AcpFilledFormAttachedPersons { get; set; }
        public virtual ICollection<MhcssIndividualClientSupportPackage> MhcssIndividualClientSupportPackages { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments { get; set; }
        public virtual ICollection<MhcssYouthResidentialRehab> MhcssYouthResidentialRehabs { get; set; }
    }
}
