//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPublicHoliday
    {
        public System.Guid fldPublicHolidayID { get; set; }
        public System.DateTime fldPublicHolidayDate { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldEdit { get; set; }
        public Nullable<System.DateTime> fldStartTime { get; set; }
        public Nullable<System.DateTime> fldEndTime { get; set; }
        public bool fldLimitTimes { get; set; }
        public Nullable<System.Guid> fldRateTypeID { get; set; }
        public bool fldAddShifts { get; set; }
        public Nullable<System.Guid> fldServiceID { get; set; }
        public Nullable<System.Guid> fldFundingBodyID { get; set; }
        public Nullable<System.Guid> fldClientID { get; set; }
    }
}
