//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonOtherType
    {
        public tblPersonOtherType()
        {
            this.tblPersonsOtherTypes = new HashSet<tblPersonsOtherType>();
        }
    
        public System.Guid fldPersonOtherTypeId { get; set; }
        public string fldPersonOtherType { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldEdit { get; set; }
        public bool fldManager { get; set; }
    
        public virtual ICollection<tblPersonsOtherType> tblPersonsOtherTypes { get; set; }
    }
}
