//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonPlanGoalsHistory
    {
        public System.Guid fldHistoryID { get; set; }
        public Nullable<System.Guid> fldID { get; set; }
        public Nullable<System.Guid> fldPlanId { get; set; }
        public string fldGoal { get; set; }
        public string fldStrategy { get; set; }
        public string fldResponsibility { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<int> fldReportingGroup { get; set; }
        public Nullable<System.DateTime> fldTargetDate { get; set; }
        public Nullable<System.DateTime> fldCompletedDate { get; set; }
        public string fldCompletedBy { get; set; }
        public string fldResultsAchieved { get; set; }
        public string fldIDNumber { get; set; }
        public Nullable<System.Guid> fldFocus { get; set; }
        public Nullable<System.Guid> fldAchieved { get; set; }
        public string fldAuditText { get; set; }
    }
}
