//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonServiceHistory
    {
        public System.Guid fldPersonServiceIDHistoryID { get; set; }
        public Nullable<System.Guid> fldPersonServiceID { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldServiceID { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public Nullable<System.Guid> fldPaybandID { get; set; }
        public Nullable<decimal> fldForecastRate { get; set; }
        public Nullable<System.Guid> fldAward { get; set; }
        public Nullable<decimal> fldRateOfPay { get; set; }
        public Nullable<System.Guid> fldEmploymentBasisId { get; set; }
    }
}
