//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonNote
    {
        public System.Guid fldPersonNoteId { get; set; }
        public System.Guid fldPersonId { get; set; }
        public System.Guid fldNoteRecievedViaTypeId { get; set; }
        public System.Guid fldGeneralNoteTypeId { get; set; }
        public string fldNote { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldForeignId { get; set; }
        public Nullable<System.DateTime> fldNoteDate { get; set; }
        public Nullable<System.Guid> fldNoteThread { get; set; }
        public Nullable<System.Guid> fldWrittenBy { get; set; }
        public bool fldMobileNote { get; set; }
        public Nullable<int> fldObjectType { get; set; }
        public Nullable<System.Guid> fldPositionID { get; set; }
        public bool fldArchived { get; set; }
        public Nullable<System.Guid> fldArchiveReason { get; set; }
        public Nullable<System.Guid> fldDescriptorId { get; set; }
        public bool fldNonDisclosure { get; set; }
        public bool fldHandoverNote { get; set; }
    }
}
