//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonDepartment
    {
        public Nullable<System.Guid> fldDepartmentID { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public System.Guid fldPersonDepartmentID { get; set; }
        public Nullable<System.Guid> fldCoordinatorID { get; set; }
        public string fldEmployeeCode { get; set; }
        public string fldCaseNumber { get; set; }
        public Nullable<System.Guid> fldCaseManagerID { get; set; }
        public Nullable<System.Guid> fldDecisionMakerID { get; set; }
        public bool fldIsDefault { get; set; }
    }
}
