//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPOA
    {
        public System.Guid fldPOAID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<int> fldDomestic { get; set; }
        public Nullable<int> fldPersonal { get; set; }
        public Nullable<int> fldCognition { get; set; }
        public Nullable<int> fldBehaviour { get; set; }
        public Nullable<int> fldCarerAvailability { get; set; }
        public Nullable<int> fldCarerStatus { get; set; }
        public Nullable<int> fldNutrition { get; set; }
        public Nullable<int> fldCommunication { get; set; }
        public Nullable<int> fldSelfRatedHealth { get; set; }
        public Nullable<int> fldSensoryVision { get; set; }
        public Nullable<int> fldSensoryHearing { get; set; }
        public Nullable<int> fldFallsRisk { get; set; }
        public Nullable<int> fldSocial { get; set; }
        public Nullable<int> fldEnvironmental { get; set; }
        public Nullable<int> fldSubtotal { get; set; }
        public string fldOther { get; set; }
        public Nullable<int> fldOtherScore { get; set; }
        public Nullable<int> fldTotal { get; set; }
        public Nullable<System.DateTime> fldDate { get; set; }
        public Nullable<System.Guid> fldAssessmentOfficer { get; set; }
    }
}
