//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonLeave
    {
        public System.Guid fldID { get; set; }
        public System.Guid fldPersonID { get; set; }
        public Nullable<System.DateTime> fldStartDate { get; set; }
        public Nullable<System.DateTime> fldEndDate { get; set; }
        public Nullable<System.Guid> fldReasonID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public bool fldAllShifts { get; set; }
        public Nullable<System.DateTime> fldStartTime { get; set; }
        public Nullable<System.DateTime> fldEndTime { get; set; }
        public bool fldShiftRejects { get; set; }
        public Nullable<System.Guid> fldReplacementCarer { get; set; }
        public bool fldCarerLeave { get; set; }
        public Nullable<System.Guid> fldLeaveClient { get; set; }
        public Nullable<System.Guid> fldLeaveFundingBody { get; set; }
        public Nullable<System.Guid> fldLeaveService { get; set; }
        public Nullable<decimal> fldPayHours { get; set; }
        public int fldPayBy { get; set; }
        public bool fldNoAction { get; set; }
        public string fldAuditText { get; set; }
        public bool fldExpiredCheckLeave { get; set; }
        public int fldLeavePersonType { get; set; }
    }
}
