//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonEventOutcome
    {
        public System.Guid fldPersonEventOutcomeId { get; set; }
        public System.Guid fldPersonEventTypeId { get; set; }
        public string fldPersonEventOutcome { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public bool fldActive { get; set; }
        public bool fldEdit { get; set; }
        public System.Guid fldUserId { get; set; }
    }
}
