//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQDCTable
    {
        public tblQDCTable()
        {
            this.MhcssIndividualClientSupportPackages = new HashSet<MhcssIndividualClientSupportPackage>();
            this.MhcssIndividualClientSupportPackages1 = new HashSet<MhcssIndividualClientSupportPackage>();
            this.MhcssIndividualClientSupportPackages2 = new HashSet<MhcssIndividualClientSupportPackage>();
            this.MhcssIntakeAssessments = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments1 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments2 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments3 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments4 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments5 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments6 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments7 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments8 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments9 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments10 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments11 = new HashSet<MhcssIntakeAssessment>();
            this.MhcssYouthResidentialRehabs = new HashSet<MhcssYouthResidentialRehab>();
            this.MhcssYouthResidentialRehabs1 = new HashSet<MhcssYouthResidentialRehab>();
            this.MhcssYouthResidentialRehabs2 = new HashSet<MhcssYouthResidentialRehab>();
            this.MhcssYouthResidentialRehabs3 = new HashSet<MhcssYouthResidentialRehab>();
            this.MhcssYouthResidentialRehabs4 = new HashSet<MhcssYouthResidentialRehab>();
        }
    
        public System.Guid fldID { get; set; }
        public Nullable<int> fldCode { get; set; }
        public string fldDescription { get; set; }
        public Nullable<int> fldCodeSet { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public string fldType { get; set; }
        public string fldESTDescription { get; set; }
    
        public virtual ICollection<MhcssIndividualClientSupportPackage> MhcssIndividualClientSupportPackages { get; set; }
        public virtual ICollection<MhcssIndividualClientSupportPackage> MhcssIndividualClientSupportPackages1 { get; set; }
        public virtual ICollection<MhcssIndividualClientSupportPackage> MhcssIndividualClientSupportPackages2 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments1 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments2 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments3 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments4 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments5 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments6 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments7 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments8 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments9 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments10 { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments11 { get; set; }
        public virtual ICollection<MhcssYouthResidentialRehab> MhcssYouthResidentialRehabs { get; set; }
        public virtual ICollection<MhcssYouthResidentialRehab> MhcssYouthResidentialRehabs1 { get; set; }
        public virtual ICollection<MhcssYouthResidentialRehab> MhcssYouthResidentialRehabs2 { get; set; }
        public virtual ICollection<MhcssYouthResidentialRehab> MhcssYouthResidentialRehabs3 { get; set; }
        public virtual ICollection<MhcssYouthResidentialRehab> MhcssYouthResidentialRehabs4 { get; set; }
    }
}
