//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuote
    {
        public System.Guid fldQuoteID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public int fldQuoteNumber { get; set; }
        public Nullable<System.Guid> fldQuoteStatusID { get; set; }
        public Nullable<System.DateTime> fldQuoteDate { get; set; }
        public Nullable<System.Guid> fldClientID { get; set; }
        public Nullable<System.Guid> fldServicesRequiredID { get; set; }
        public Nullable<decimal> fldHours { get; set; }
        public string fldWorkerNotes { get; set; }
        public Nullable<System.Guid> fldCarerID { get; set; }
        public bool fldVerbalApproval { get; set; }
        public Nullable<decimal> fldRate { get; set; }
        public Nullable<decimal> fldTotalCharge { get; set; }
    }
}
