//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResidentialServicesGoalHeader
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldResidentialServicesId { get; set; }
        public bool fldNoAction { get; set; }
        public string fldConcerns { get; set; }
        public string fldStrength { get; set; }
        public string fldGoals { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<int> fldCarePlanType { get; set; }
        public bool fldIsHeader { get; set; }
    }
}
