//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReminder
    {
        public System.Guid fldReminderID { get; set; }
        public string fldNote { get; set; }
        public Nullable<System.DateTime> fldReminderDate { get; set; }
        public Nullable<byte> fldSendViaCarelink { get; set; }
        public Nullable<byte> fldSendViaEmail { get; set; }
        public Nullable<byte> fldActioned { get; set; }
        public Nullable<System.DateTime> fldDateActioned { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.DateTime> fldReminderTime { get; set; }
        public string fldSubject { get; set; }
        public Nullable<System.Guid> fldForeignId { get; set; }
        public Nullable<System.Guid> fldWrittenBy { get; set; }
        public Nullable<System.Guid> fldBusinessBaseId { get; set; }
        public int fldObjectType { get; set; }
        public Nullable<System.DateTime> fldDueDate { get; set; }
        public string fldNotification { get; set; }
        public bool fldNotificationSent { get; set; }
        public bool fldOnlineReminder { get; set; }
        public Nullable<System.Guid> fldResponseID { get; set; }
        public Nullable<System.Guid> fldActionedUserId { get; set; }
        public string fldActionsTaken { get; set; }
    }
}
