//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRisk
    {
        public System.Guid fldRiskID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public string fldFactorsCommAccess { get; set; }
        public string fldFactorsTransport { get; set; }
        public string fldFactorsPersonalSupport { get; set; }
        public string fldFactorsSafety { get; set; }
        public string fldFactorsMobility { get; set; }
        public string fldFactorsBehaviour { get; set; }
        public string fldStrategyCommAccess { get; set; }
        public string fldStrategyTransport { get; set; }
        public string fldStrategyPersonalSupport { get; set; }
        public string fldStrategySafety { get; set; }
        public string fldStrategyMobility { get; set; }
        public string fldStrategyBehaviour { get; set; }
    }
}
