//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecurrence2History
    {
        public System.Guid fldRecurrenceHistoryId { get; set; }
        public Nullable<System.Guid> fldRecurrenceId { get; set; }
        public string fldPattern { get; set; }
        public Nullable<System.DateTime> fldPatternStartDate { get; set; }
        public Nullable<System.DateTime> fldPatternEndDate { get; set; }
        public Nullable<System.DateTime> fldFirstStartDate { get; set; }
        public Nullable<System.DateTime> fldLastEndDate { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public string fldShortDescription { get; set; }
        public string fldLongDescription { get; set; }
        public string fldWeekNumber { get; set; }
        public string fldDays { get; set; }
        public Nullable<byte> fldNoEndDate { get; set; }
    }
}
