//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportRequirement
    {
        public System.Guid fldID { get; set; }
        public System.Guid fldParentID { get; set; }
        public string fldName { get; set; }
        public string fldValue { get; set; }
        public int fldComparison { get; set; }
        public byte fldIncludeUndefined { get; set; }
    }
}
