//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRosterTask
    {
        public System.Guid fldRosterTasksId { get; set; }
        public Nullable<System.Guid> fldRosterRuleId { get; set; }
        public Nullable<System.Guid> fldRosterShiftID { get; set; }
        public System.Guid fldTaskId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<decimal> fldPercentTime { get; set; }
        public Nullable<decimal> fldIndirectTime { get; set; }
        public Nullable<System.Guid> fldTaskCategoryId { get; set; }
    }
}
