//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoster2HomecareHistory
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldRosterShiftId { get; set; }
        public Nullable<System.Guid> fldRosterRuleId { get; set; }
        public Nullable<System.DateTime> fldStartTime { get; set; }
        public Nullable<System.DateTime> fldEndTime { get; set; }
        public Nullable<System.Guid> fldClientId { get; set; }
        public Nullable<System.Guid> fldCarerId { get; set; }
        public Nullable<System.Guid> fldFundingId { get; set; }
        public Nullable<bool> fldIsApproved { get; set; }
        public Nullable<bool> fldIsManuallyEdited { get; set; }
        public Nullable<bool> fldIsMaster { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<bool> fldIsFrozen { get; set; }
        public Nullable<System.Guid> fldFrozenReasonId { get; set; }
        public Nullable<System.Guid> fldFrozenUserId { get; set; }
        public Nullable<System.Guid> fldGroupId { get; set; }
        public Nullable<decimal> fldExpenses { get; set; }
        public Nullable<decimal> fldTravelDistance { get; set; }
        public Nullable<decimal> fldTravelDistanceInt { get; set; }
        public Nullable<short> fldTravelTime { get; set; }
        public Nullable<int> fldFlag { get; set; }
        public Nullable<bool> fldIsClashing { get; set; }
        public string fldAuditText { get; set; }
        public bool fldIsDeleted { get; set; }
        public int fldIsRejected { get; set; }
        public Nullable<System.DateTime> fldUpdatedFrom { get; set; }
        public bool fldIgnorePayMinimum { get; set; }
        public bool fldCancelled { get; set; }
        public Nullable<int> fldMealBreak { get; set; }
        public Nullable<int> fldMeals { get; set; }
        public bool fldPaySupplier { get; set; }
        public Nullable<System.Guid> fldHomeMaintenanceId { get; set; }
        public Nullable<System.Guid> fldLinkedShiftId { get; set; }
        public Nullable<System.Guid> fldRegionId { get; set; }
        public Nullable<int> fldApprovalType { get; set; }
        public Nullable<System.DateTime> fldOriginalShiftDate { get; set; }
        public Nullable<decimal> fldExpensesInt { get; set; }
        public Nullable<System.DateTime> fldWorkedStartTime { get; set; }
        public Nullable<System.DateTime> fldWorkedEndTime { get; set; }
        public Nullable<System.DateTime> fldRosteredStartTime { get; set; }
        public Nullable<System.DateTime> fldRosteredEndTime { get; set; }
        public Nullable<System.Guid> fldActivityID { get; set; }
        public Nullable<System.Guid> fldFacilityID { get; set; }
        public Nullable<bool> fldSubmitted { get; set; }
        public Nullable<int> fldImportStatus { get; set; }
        public string fldOrderNumber { get; set; }
        public Nullable<decimal> fldTotalCharge { get; set; }
        public Nullable<bool> fldExcludeTravel { get; set; }
        public Nullable<bool> fldExcludeTravelManualUpdate { get; set; }
        public Nullable<System.Guid> fldExcludeTravelReason { get; set; }
        public bool fldCarerEdit { get; set; }
        public Nullable<System.Guid> fldAttendeeID { get; set; }
        public Nullable<System.Guid> fldUserDef1 { get; set; }
        public Nullable<System.Guid> fldUserDef2 { get; set; }
        public Nullable<System.Guid> fldUserDef3 { get; set; }
        public Nullable<System.Guid> fldActivityTypeID { get; set; }
        public Nullable<System.Guid> fldCancellationChargeReasonId { get; set; }
        public Nullable<System.Guid> fldPaybandID { get; set; }
        public Nullable<decimal> fldRateofPay { get; set; }
        public Nullable<bool> fldIsRecall { get; set; }
        public Nullable<bool> fldManualKilometreOverride { get; set; }
        public Nullable<bool> fldManualTravelTimeOverride { get; set; }
        public bool fldSubmittedViaCLM { get; set; }
        public Nullable<bool> fldExcludeExpenses { get; set; }
        public Nullable<decimal> fldOverrideCharge { get; set; }
        public bool fldMentalHealthSpecificGroup { get; set; }
        public Nullable<decimal> fldTotalCost { get; set; }
        public Nullable<decimal> fldForecastCost { get; set; }
        public Nullable<System.DateTime> fldDateApproved { get; set; }
        public Nullable<System.Guid> fldShiftStartGeographicCoordinateId { get; set; }
        public Nullable<System.Guid> fldShiftEndGeographicCoordinateId { get; set; }
        public string fldScanReferenceUrl { get; set; }
        public bool fldNoCharge { get; set; }
        public Nullable<System.Guid> fldClientFundingSource { get; set; }
        public bool fldIsFreeService { get; set; }
        public Nullable<System.Guid> fldProfessionalServiceAllowance { get; set; }
        public Nullable<System.Guid> fldRosterRatio { get; set; }
        public Nullable<short> fldOriginalTravelTime { get; set; }
        public Nullable<decimal> fldOriginalTravelDistance { get; set; }
        public Nullable<decimal> fldOriginalTravelDistanceInt { get; set; }
    }
}
