//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRosterImportReject
    {
        public int fldID { get; set; }
        public Nullable<System.DateTime> fldStartTime { get; set; }
        public Nullable<System.DateTime> fldEndTime { get; set; }
        public Nullable<double> fldTotalHours { get; set; }
        public Nullable<System.DateTime> fldShiftDate { get; set; }
        public Nullable<float> fldKilometres { get; set; }
        public Nullable<int> fldImportID { get; set; }
        public Nullable<decimal> fldExpenses { get; set; }
        public Nullable<System.Guid> fldCarerID { get; set; }
        public Nullable<System.Guid> fldRosterID { get; set; }
        public Nullable<System.Guid> fldServiceID { get; set; }
        public Nullable<System.Guid> fldClientID { get; set; }
        public Nullable<System.Guid> fldFundingBodyID { get; set; }
        public bool fldKilExpFlag { get; set; }
    }
}
