//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportSummary
    {
        public int fldReportID { get; set; }
        public string fldReportName { get; set; }
        public bool fldExportToCSV { get; set; }
        public bool fldEmailReport { get; set; }
        public string fldEmailContent { get; set; }
    }
}
