//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRosterScenario
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldRecurrenceId { get; set; }
        public Nullable<decimal> fldHours { get; set; }
        public Nullable<System.Guid> fldCarerId { get; set; }
        public Nullable<System.Guid> fldFundingId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldClientId { get; set; }
        public string fldDescription { get; set; }
        public Nullable<decimal> fldTotalHours { get; set; }
        public Nullable<decimal> fldCharges { get; set; }
        public Nullable<decimal> fldCost { get; set; }
        public Nullable<System.DateTime> fldStartDate { get; set; }
        public Nullable<System.DateTime> fldEndDate { get; set; }
        public Nullable<System.Guid> fldRosterRuleId { get; set; }
    }
}
