//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRateTypesHistory
    {
        public System.Guid fldRateTypeIDHistoryID { get; set; }
        public Nullable<System.Guid> fldRateTypeID { get; set; }
        public string fldRateType { get; set; }
        public string fldDescription { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<byte> fldEdit { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public Nullable<System.DateTime> fldStartTime { get; set; }
        public Nullable<System.DateTime> fldEndTime { get; set; }
        public bool fldAllowAddCharge { get; set; }
        public bool fldExcludeHighestRate { get; set; }
        public bool fldMDSHomeModification { get; set; }
        public bool fldIncludeInMakeupPay { get; set; }
        public bool fldUseForMakeupPay { get; set; }
    }
}
