//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResidentialServicesBehaviour
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldResidentialServicesId { get; set; }
        public Nullable<System.DateTime> fldObservationDate { get; set; }
        public string fldObservedEvent { get; set; }
        public string fldObservedLocation { get; set; }
        public string fldObservedFollowup { get; set; }
        public string fldObservationComments { get; set; }
        public Nullable<System.Guid> fldObserverId { get; set; }
        public string fldObservedPrior { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
    }
}
