//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRosterMaterial
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldRosterShiftId { get; set; }
        public Nullable<System.Guid> fldMaterialId { get; set; }
        public Nullable<decimal> fldQuantity { get; set; }
        public Nullable<decimal> fldCost { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<decimal> fldUnitCost { get; set; }
        public Nullable<decimal> fldTaxAmount { get; set; }
        public Nullable<decimal> fldTotalCost { get; set; }
        public Nullable<System.Guid> fldSupplierId { get; set; }
        public string fldSupplierName { get; set; }
        public string fldInvoiceNumber { get; set; }
        public Nullable<System.DateTime> fldInvoiceDate { get; set; }
        public bool fldGSTExempt { get; set; }
        public Nullable<decimal> fldExportAmount { get; set; }
        public Nullable<System.Guid> fldExportId { get; set; }
    }
}
