//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResidentialServicesGoalReview
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldResidentialServicesGoalId { get; set; }
        public Nullable<System.Guid> fldReviewTypeId { get; set; }
        public Nullable<System.Guid> fldReviewedById { get; set; }
        public string fldAchieved { get; set; }
        public string fldNotAchieved { get; set; }
        public string fldConcerns { get; set; }
        public bool fldStakeholderMeeting { get; set; }
        public Nullable<System.DateTime> fldScheduleDate { get; set; }
        public string fldMeetingElements { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.DateTime> fldReviewDate { get; set; }
    }
}
