//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegion
    {
        public System.Guid fldRegionID { get; set; }
        public string fldRegion { get; set; }
        public Nullable<System.Guid> fldStateId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldEdit { get; set; }
        public string fldExportCode { get; set; }
        public Nullable<int> fldSearchRadius { get; set; }
        public string fldEziPayRegion { get; set; }
        public string fldRegionCode { get; set; }
        public string fldExchangeURI { get; set; }
        public string fldExchangeCarerURI { get; set; }
        public string fldCompanyCode { get; set; }
        public string fldNDISRegionCode { get; set; }
    }
}
