//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScriptHistory
    {
        public System.Guid fldID { get; set; }
        public string fldScriptName { get; set; }
        public Nullable<System.DateTime> fldDateTime { get; set; }
        public string fldUser { get; set; }
    }
}
