//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSHSHistory
    {
        public System.Guid fldSHSID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<int> fldType { get; set; }
        public Nullable<System.Guid> fldFundingDetailID { get; set; }
        public Nullable<int> fldNewToAgency { get; set; }
        public bool fldConsentReceived { get; set; }
        public Nullable<System.Guid> fldCareArrangementBefore { get; set; }
        public Nullable<int> fldMentalHealth { get; set; }
        public Nullable<System.Guid> fldReferralSource { get; set; }
        public Nullable<System.Guid> fldAssistanceTimePeriod { get; set; }
        public Nullable<System.Guid> fldAdditionalInformation { get; set; }
        public Nullable<System.Guid> fldMainAssistanceReason { get; set; }
        public Nullable<System.Guid> fldPreviousHomlessnessMonth { get; set; }
        public Nullable<System.Guid> fldPreviousHomlessness12Months { get; set; }
        public Nullable<System.Guid> fldLastPermanent { get; set; }
        public Nullable<int> fldLastPermanentLastWeek { get; set; }
        public Nullable<System.Guid> fldSuburbLastWeek { get; set; }
        public bool fldSuburbLastWeekUnknown { get; set; }
        public bool fldLastPermanentUnknown { get; set; }
        public Nullable<System.Guid> fldLastPermanentSuburb { get; set; }
        public Nullable<System.Guid> fldLivingArrangementBefore { get; set; }
        public Nullable<System.Guid> fldCareArrangementPresenting { get; set; }
        public Nullable<System.Guid> fldLivingArrangementPresenting { get; set; }
        public Nullable<System.Guid> fldTenureBefore { get; set; }
        public Nullable<System.Guid> fldTenurePresenting { get; set; }
        public Nullable<System.Guid> fldOccupancyConditionBefore { get; set; }
        public Nullable<System.Guid> fldOccupancyConditionPresenting { get; set; }
        public Nullable<System.Guid> fldLabourForceStatusBefore { get; set; }
        public Nullable<System.Guid> fldLabourForceStatusPresenting { get; set; }
        public Nullable<System.Guid> fldEmploymentStatusBefore { get; set; }
        public Nullable<System.Guid> fldEmploymentStatusPresenting { get; set; }
        public Nullable<System.Guid> fldIncomeSourceBefore { get; set; }
        public Nullable<System.Guid> fldIncomeSourcePresenting { get; set; }
        public Nullable<int> fldGovtBenefitBefore { get; set; }
        public Nullable<int> fldGovtBenefitPresenting { get; set; }
        public Nullable<int> fldStudyBefore { get; set; }
        public Nullable<int> fldStudyPresenting { get; set; }
        public Nullable<System.Guid> fldEducationBefore { get; set; }
        public Nullable<System.Guid> fldEducationPresenting { get; set; }
        public Nullable<System.Guid> fldSchoolEnrolementPresenting { get; set; }
        public Nullable<int> fldPaymentShortTerm { get; set; }
        public Nullable<int> fldPaymentEstablish { get; set; }
        public Nullable<int> fldPaymentEducation { get; set; }
        public Nullable<int> fldPaymentExternal { get; set; }
        public Nullable<int> fldPaymentOther { get; set; }
        public Nullable<System.Guid> fldServiceCareArrangment { get; set; }
        public bool fldCaseManagement { get; set; }
        public Nullable<System.Guid> fldCaseManagementReason { get; set; }
        public string fldCaseManagementReasonOther { get; set; }
        public Nullable<System.Guid> fldCaseManagementGoal { get; set; }
        public Nullable<System.Guid> fldHomelessLastMonth { get; set; }
        public Nullable<System.Guid> fldServiceLivingArrangement { get; set; }
        public Nullable<System.Guid> fldResidenceBefore { get; set; }
        public Nullable<System.Guid> fldResidencePresenting { get; set; }
        public Nullable<System.Guid> fldServiceResidence { get; set; }
        public Nullable<System.Guid> fldServiceTenure { get; set; }
        public Nullable<System.Guid> fldServiceOccupancyCondition { get; set; }
        public Nullable<System.Guid> fldServiceLabourForceStatus { get; set; }
        public Nullable<System.Guid> fldServiceEmploymentStatus { get; set; }
        public Nullable<System.Guid> fldServiceIncomeSource { get; set; }
        public Nullable<int> fldServiceStudy { get; set; }
        public Nullable<System.Guid> fldServiceEducation { get; set; }
        public Nullable<System.Guid> fldPeriodEndReason { get; set; }
        public Nullable<int> fldSupportPeriodOngoing { get; set; }
        public Nullable<System.Guid> fldDOBAccuracyDay { get; set; }
        public Nullable<System.Guid> fldDOBAccuracyMonth { get; set; }
        public Nullable<System.Guid> fldDOBAccuracyYear { get; set; }
        public Nullable<System.DateTime> fldDateServiceRequested { get; set; }
        public Nullable<int> fldFirstRequest { get; set; }
        public Nullable<System.Guid> fldServiceRequestedWhen { get; set; }
        public Nullable<System.DateTime> fldExportDate { get; set; }
        public Nullable<int> fldServiceGovtBenefit { get; set; }
        public Nullable<int> fldUnassistedPersonID { get; set; }
        public Nullable<System.DateTime> fldOriginalCollectionMonth { get; set; }
        public Nullable<System.DateTime> fldSupportPeriodCommenced { get; set; }
        public Nullable<System.Guid> fldUnassistedAgencyID { get; set; }
        public Nullable<System.Guid> fldExportId { get; set; }
        public Nullable<System.Guid> fldSelfCareAssistance { get; set; }
        public Nullable<System.Guid> fldMobilityAssistance { get; set; }
        public Nullable<System.Guid> fldCommunicationAssistance { get; set; }
        public System.Guid fldSHSHistoryID { get; set; }
        public string fldHistoryStatus { get; set; }
    }
}
