//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSDMSafety
    {
        public System.Guid fldSDMSafetyID { get; set; }
        public System.Guid fldPersonID { get; set; }
        public Nullable<System.Guid> fldPrimaryCarerID { get; set; }
        public Nullable<System.Guid> fldSecondaryCarerID { get; set; }
        public Nullable<bool> fldIsAllegation { get; set; }
        public Nullable<System.Guid> fldTeam { get; set; }
        public Nullable<System.Guid> fldWorkerID { get; set; }
        public Nullable<System.DateTime> fldAssessmentDate { get; set; }
        public Nullable<bool> fldAboriginalorTorres { get; set; }
        public Nullable<bool> fldIsRefugee { get; set; }
        public bool fldAgedUnder5 { get; set; }
        public bool fldSignificantDiagnosedIllness { get; set; }
        public bool fldDiminishedIntellecutal { get; set; }
        public bool fldDevelopmentalDisability { get; set; }
        public bool fldDiminishedPhysicalCapacity { get; set; }
        public bool fldSignificantBehaviouralProblems { get; set; }
        public bool fldLimitedVisibility { get; set; }
        public bool fldCPACheck1 { get; set; }
        public bool fldCPACheck2 { get; set; }
        public bool fldCPACheck3 { get; set; }
        public bool fldCPACheck4 { get; set; }
        public bool fldCPACheck5 { get; set; }
        public bool fldCPACheck6 { get; set; }
        public bool fldCPACheck7 { get; set; }
        public bool fldCPACheck8 { get; set; }
        public bool fldCPACheck9 { get; set; }
        public bool fldCPACheck10 { get; set; }
        public bool fldCPACheck11 { get; set; }
        public string fldCPACheck11OtherText { get; set; }
        public bool fldSaftetyInvnCheck1 { get; set; }
        public bool fldSaftetyInvnCheck2 { get; set; }
        public bool fldSaftetyInvnCheck3 { get; set; }
        public bool fldSaftetyInvnCheck4 { get; set; }
        public bool fldSaftetyInvnCheck5 { get; set; }
        public bool fldSaftetyInvnCheck6 { get; set; }
        public bool fldSaftetyInvnCheck7 { get; set; }
        public bool fldSaftetyInvnCheck8 { get; set; }
        public bool fldSaftetyInvnCheck9 { get; set; }
        public string fldSaftetyInvnCheck8OtherText { get; set; }
        public Nullable<bool> fldSafetyDecisionHelpline { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<bool> fldActive { get; set; }
        public Nullable<System.Guid> fldPersonCaseNumberFamilyId { get; set; }
        public bool fldIsInitial { get; set; }
        public bool fldIsReview { get; set; }
        public bool fldIsCaseClosing { get; set; }
        public bool fldSafetyDecisionIsSafe { get; set; }
        public bool fldSafetyDecisionIsSafeWithPlan { get; set; }
        public bool fldSafetyDecisionIsUnsafe { get; set; }
        public Nullable<System.DateTime> fldFirstContactDate { get; set; }
        public Nullable<System.DateTime> fldSafetyDecisionHelplineDateTime { get; set; }
        public string fldCommunityServicesHelplineWorker { get; set; }
        public bool fldCommunityServicesFullResponsibility { get; set; }
        public bool fldCommunityServicesParticipate { get; set; }
        public bool fldBrighterFuturesContinueWork { get; set; }
        public bool fldCommunityServicesEvaluating { get; set; }
        public bool fldBrighterFuturesAwaiting { get; set; }
        public Nullable<System.Guid> fldWorkerSuperviserId { get; set; }
        public Nullable<System.DateTime> fldWorkSupervisorDate { get; set; }
        public Nullable<System.Guid> fldFamilyCultureId { get; set; }
    }
}
