//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheduleServicesHistory
    {
        public System.Guid fldScheduleServiceIdHistoryID { get; set; }
        public Nullable<System.Guid> fldScheduleServiceId { get; set; }
        public Nullable<System.Guid> fldScheduleId { get; set; }
        public Nullable<System.Guid> fldServiceId { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public Nullable<System.Guid> fldScheduleDatesID { get; set; }
        public Nullable<int> fldFlatRateSplit { get; set; }
    }
}
