//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuburb
    {
        public tblSuburb()
        {
            this.MhcssIntakeAssessments = new HashSet<MhcssIntakeAssessment>();
            this.MhcssIntakeAssessments1 = new HashSet<MhcssIntakeAssessment>();
        }
    
        public System.Guid fldSuburbID { get; set; }
        public string fldSuburb { get; set; }
        public Nullable<System.Guid> fldPostCodeID { get; set; }
        public Nullable<System.Guid> fldRegionID { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldEdit { get; set; }
        public Nullable<int> fldMDSCode { get; set; }
        public string fldPostcode { get; set; }
        public Nullable<System.Guid> fldState { get; set; }
        public Nullable<System.Guid> fldTransportZone { get; set; }
        public Nullable<System.Guid> fldLGA { get; set; }
        public Nullable<System.Guid> fldRemotenessAreaID { get; set; }
        public Nullable<System.Guid> fldOfficeID { get; set; }
        public Nullable<System.Guid> fldPlanningRegionID { get; set; }
    
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments1 { get; set; }
    }
}
