//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceTask
    {
        public System.Guid fldTasksID { get; set; }
        public System.Guid fldServiceID { get; set; }
        public string fldTasks { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public byte fldActive { get; set; }
        public byte fldEdit { get; set; }
        public Nullable<System.Guid> fldTaskID { get; set; }
        public bool fldPercentRequired { get; set; }
        public bool fldIndirectPercentage { get; set; }
        public Nullable<System.Guid> fldTaskCategoryId { get; set; }
    }
}
