//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportTripHistory
    {
        public System.Guid fldTransportTripHistoryId { get; set; }
        public System.Guid fldTransportTripId { get; set; }
        public bool fldActive { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public System.Guid fldStartLocationId { get; set; }
        public System.Guid fldEndLocationId { get; set; }
        public Nullable<System.Guid> fldTransportJourneyTypeId { get; set; }
        public string fldNotes { get; set; }
        public Nullable<System.Guid> fldPreviousTripId { get; set; }
        public Nullable<System.Guid> fldNextTripId { get; set; }
        public bool fldIsManuallyEdited { get; set; }
        public Nullable<System.Guid> fldTransportTripRuleId { get; set; }
        public Nullable<System.Guid> fldRecurrenceId { get; set; }
        public Nullable<System.Guid> fldRecurrenceGeneratedDateId { get; set; }
    }
}
