//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimesheetAllowance
    {
        public System.Guid fldID { get; set; }
        public Nullable<System.Guid> fldCarerId { get; set; }
        public Nullable<System.Guid> fldAllowanceId { get; set; }
        public Nullable<decimal> fldValue { get; set; }
        public Nullable<System.DateTime> fldAllowanceDate { get; set; }
        public Nullable<System.DateTime> fldPayDate { get; set; }
        public Nullable<System.Guid> fldServiceId { get; set; }
        public Nullable<System.Guid> fldRosterShiftId { get; set; }
        public Nullable<System.Guid> fldRateTypeId { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<bool> fldActive { get; set; }
        public Nullable<System.DateTime> fldExportDate { get; set; }
        public Nullable<System.Guid> fldPayrate { get; set; }
        public Nullable<System.Guid> fldExportId { get; set; }
        public bool fldManualEntry { get; set; }
        public bool fldReversal { get; set; }
        public Nullable<decimal> fldRateOfPay { get; set; }
        public string fldAuditText { get; set; }
    }
}
