//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportJourneyLocation
    {
        public System.Guid fldTransportJourneyLocationId { get; set; }
        public bool fldActive { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<System.Guid> fldAddressId { get; set; }
        public Nullable<System.Guid> fldTransportVehicleRouteId { get; set; }
        public System.DateTime fldArrivalTime { get; set; }
        public int fldTimeToWait { get; set; }
        public Nullable<System.Guid> fldTransportJourneyLocationRuleId { get; set; }
    }
}
