//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportTripPassengerHistory
    {
        public System.Guid fldTransportTripPassengerHistoryId { get; set; }
        public System.Guid fldTransportTripPassengerId { get; set; }
        public System.Guid fldTransportTripId { get; set; }
        public bool fldActive { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public Nullable<System.Guid> fldUserId { get; set; }
        public Nullable<System.Guid> fldTransportShiftId { get; set; }
        public Nullable<System.Guid> fldPersonId { get; set; }
        public Nullable<System.Guid> fldFundingId { get; set; }
        public Nullable<System.Guid> fldContactPersonId { get; set; }
        public bool fldIsManuallyEdited { get; set; }
        public Nullable<System.Guid> fldTransportTripPassengerRuleId { get; set; }
    }
}
