//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserOption
    {
        public System.Guid fldUserOptionID { get; set; }
        public System.Guid fldUserId { get; set; }
        public int fldDefaultRoster { get; set; }
        public bool fldSpellCheckAYT { get; set; }
        public bool fldNoShowReminder { get; set; }
        public bool fldMobileReminders { get; set; }
    }
}
