//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.AcpActionItems = new HashSet<AcpActionItem>();
            this.AcpFilledForms = new HashSet<AcpFilledForm>();
            this.AcpSectionQuestions = new HashSet<AcpSectionQuestion>();
            this.AcpTemplateVersions = new HashSet<AcpTemplateVersion>();
            this.MhcssIndividualClientSupportPackages = new HashSet<MhcssIndividualClientSupportPackage>();
            this.MhcssIntakeAssessments = new HashSet<MhcssIntakeAssessment>();
            this.MhcssYouthResidentialRehabs = new HashSet<MhcssYouthResidentialRehab>();
            this.Quotations = new HashSet<Quotation>();
            this.QuotationExternalOutgoings = new HashSet<QuotationExternalOutgoing>();
            this.QuotationExternalOutgoingRecurrings = new HashSet<QuotationExternalOutgoingRecurring>();
            this.QuotationIncomeSources = new HashSet<QuotationIncomeSource>();
            this.QuotationInternalOutgoings = new HashSet<QuotationInternalOutgoing>();
            this.QuotationOtherCharges = new HashSet<QuotationOtherCharge>();
            this.QuotationRecurringExternalOutgoings = new HashSet<QuotationRecurringExternalOutgoing>();
            this.tblUserRoles = new HashSet<tblUserRole>();
        }
    
        public System.Guid fldUserId { get; set; }
        public string fldUserName { get; set; }
        public string fldUserPassword { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public byte fldActive { get; set; }
        public string fldFullName { get; set; }
        public Nullable<System.Guid> fldModifiedUserId { get; set; }
        public string fldEmailAddress { get; set; }
        public bool fldUseAsServerLogin { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldFacilityId { get; set; }
        public bool fldLimitPermissions { get; set; }
        public string fldNotes { get; set; }
        public string fldAuditNote { get; set; }
        public bool fldContractExecutor { get; set; }
        public int fldTimesheetType { get; set; }
        public Nullable<System.Guid> fldManagerID { get; set; }
        public Nullable<System.Guid> fldMyOrganisationId { get; set; }
        public Nullable<System.DateTime> fldLastPasswordChangeDate { get; set; }
        public string fldClearTextPassword { get; set; }
        public Nullable<System.Guid> fldPositionID { get; set; }
        public bool fldAcknowledgeAlerts { get; set; }
        public Nullable<System.DateTime> fldOutOfOfficeStart { get; set; }
        public Nullable<System.DateTime> fldOutOfOfficeEnd { get; set; }
        public Nullable<System.Guid> fldOutOfOfficeUserId { get; set; }
        public bool fldUseAsWebServiceAccount { get; set; }
        public Nullable<System.Guid> fldRegionID { get; set; }
        public string fldNDISLoginName { get; set; }
        public bool fldCPATbyDefault { get; set; }
        public bool fldAssmtNodebyDefault { get; set; }
    
        public virtual ICollection<AcpActionItem> AcpActionItems { get; set; }
        public virtual ICollection<AcpFilledForm> AcpFilledForms { get; set; }
        public virtual ICollection<AcpSectionQuestion> AcpSectionQuestions { get; set; }
        public virtual ICollection<AcpTemplateVersion> AcpTemplateVersions { get; set; }
        public virtual ICollection<MhcssIndividualClientSupportPackage> MhcssIndividualClientSupportPackages { get; set; }
        public virtual ICollection<MhcssIntakeAssessment> MhcssIntakeAssessments { get; set; }
        public virtual ICollection<MhcssYouthResidentialRehab> MhcssYouthResidentialRehabs { get; set; }
        public virtual ICollection<Quotation> Quotations { get; set; }
        public virtual ICollection<QuotationExternalOutgoing> QuotationExternalOutgoings { get; set; }
        public virtual ICollection<QuotationExternalOutgoingRecurring> QuotationExternalOutgoingRecurrings { get; set; }
        public virtual ICollection<QuotationIncomeSource> QuotationIncomeSources { get; set; }
        public virtual ICollection<QuotationInternalOutgoing> QuotationInternalOutgoings { get; set; }
        public virtual ICollection<QuotationOtherCharge> QuotationOtherCharges { get; set; }
        public virtual ICollection<QuotationRecurringExternalOutgoing> QuotationRecurringExternalOutgoings { get; set; }
        public virtual ICollection<tblUserRole> tblUserRoles { get; set; }
    }
}
