//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsersHistory
    {
        public Nullable<System.Guid> fldUserId { get; set; }
        public string fldUserName { get; set; }
        public string fldUserPassword { get; set; }
        public Nullable<System.DateTime> fldDateCreated { get; set; }
        public Nullable<System.DateTime> fldDateUpdated { get; set; }
        public Nullable<byte> fldActive { get; set; }
        public string fldFullName { get; set; }
        public Nullable<System.Guid> fldModifiedUserId { get; set; }
        public string fldEmailAddress { get; set; }
        public Nullable<bool> fldUseAsServerLogin { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public Nullable<System.Guid> fldFacilityId { get; set; }
        public Nullable<bool> fldLimitPermissions { get; set; }
        public System.Guid fldID { get; set; }
        public string fldNotes { get; set; }
        public string fldAuditNote { get; set; }
        public Nullable<System.Guid> fldManagerID { get; set; }
        public Nullable<System.Guid> fldMyOrganisationId { get; set; }
        public Nullable<System.Guid> fldPositionID { get; set; }
        public Nullable<bool> fldAcknowledgeAlerts { get; set; }
        public Nullable<System.DateTime> fldOutOfOfficeStart { get; set; }
        public Nullable<System.DateTime> fldOutOfOfficeEnd { get; set; }
        public Nullable<System.Guid> fldOutOfOfficeUserId { get; set; }
        public Nullable<System.Guid> fldRegionID { get; set; }
    }
}
