//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehcileDetail
    {
        public System.Guid fldVehicleDetailsID { get; set; }
        public Nullable<System.Guid> fldPersonID { get; set; }
        public System.Guid fldVehicleTypeID { get; set; }
        public Nullable<System.Guid> fldBodyTypeID { get; set; }
        public Nullable<System.Guid> fldNumCylinders { get; set; }
        public Nullable<int> fldYear { get; set; }
        public Nullable<System.Guid> fldInsuranceTypeID { get; set; }
        public Nullable<System.Guid> fldInsurerID { get; set; }
        public Nullable<System.DateTime> fldRenewalDate { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public System.Guid fldUserId { get; set; }
        public byte fldActive { get; set; }
        public Nullable<bool> fldDefaultView { get; set; }
        public string fldDescription { get; set; }
        public string fldVehicleNumber { get; set; }
        public string fldRegistrationNumber { get; set; }
        public Nullable<System.DateTime> fldRegistrationRenewal { get; set; }
        public Nullable<System.Guid> fldVehicleStatus { get; set; }
        public Nullable<int> fldSeatingCapacity { get; set; }
        public Nullable<int> fldWheelchairCapacity { get; set; }
        public Nullable<System.DateTime> fldRoadworthyReminder { get; set; }
        public Nullable<decimal> fldKilometreRate { get; set; }
        public Nullable<decimal> fldHireRate { get; set; }
        public bool fldRoadworthy { get; set; }
        public Nullable<int> fldPermanentWheelchairs { get; set; }
        public bool fldWheelchairHoist { get; set; }
        public bool fldIsCasual { get; set; }
    }
}
