//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkflowStepsHistory
    {
        public System.Guid fldID { get; set; }
        public System.Guid fldWorkflowStepId { get; set; }
        public System.Guid fldWorkflowId { get; set; }
        public System.DateTime fldDateCreated { get; set; }
        public System.DateTime fldDateUpdated { get; set; }
        public byte fldActive { get; set; }
        public System.Guid fldUserId { get; set; }
        public string fldName { get; set; }
        public short fldOrder { get; set; }
        public Nullable<System.Guid> fldParentId { get; set; }
        public string fldDescription { get; set; }
        public Nullable<System.Guid> fldFormId { get; set; }
        public short fldConditionType { get; set; }
        public string fldDiscretionaryQuestion { get; set; }
        public short fldDiscretionaryPositiveAnswer { get; set; }
        public short fldStepType { get; set; }
        public string fldConditionalExpression { get; set; }
        public string fldAttachedDocumentFileName { get; set; }
        public string fldMimeType { get; set; }
    }
}
